[msg MSG_000_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 1 0 0][nl]-san... Today's meeting is canceled.[n][w][e]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 2 0 0][f 4 21 109 11]Um, did Odagiri-san do something?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]What do you mean?[e]
[f 2 1]Why? Is something wrong?[e]

[msg MSG_002_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 3 0 0]A teacher came by earlier and called him to the faculty office.[n][w][e]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 4 0 0]That teacher seemed really upset...[n][w][e]

[msg MSG_003_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 5 0 0]He was called to the faculty office by a teacher earlier.[n][w][e]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 6 0 0]I think it's about that cigarette butt...[n][w][e]

[msg MND_004_0_0]
[f 2 1]Did something happen?[n][w][e]
[f 2 1]I better head to the faculty office.[n][w][e]

