[msg MSG_000_0_0 [Aigis]]
[f 2 1][bup 7 2 65535 65535 0 0][vp 1 0 0 1 0 0]Ah...[n][w][e]

[msg MSG_001_0_0 [Black Shiba Inu]]
[f 2 1][vp 1 0 0 2 0 0]Grrrrrr... Bark! Bark![n][w][e]

[msg MSG_002_0_0 [Brown Cat]]
[f 2 1][vp 1 0 0 3 0 0]Hisssss![n][w][e]

[msg MSG_003_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 4 0 0][nf]-san, stay behind me. This could be dangerous.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 5 0 0]They seem very angry.[n][w][e]

[msg MSG_004_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 6 0 0]...You're the ones that I often see at the shrine.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 7 0 0]What's wrong?[n][w][e]

[msg MSG_005_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 8 0 0]...What? Koromaru-san?[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 9 0 0]You think we what!?[n][w][e]

[msg MSG_006_0_0 [Aigis]]
[f 2 1][bup 7 2 65535 65535 0 0][vp 1 0 0 10 0 0]Wait! We aren't mistreating Koromaru-san![n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 11 0 0][f 4 23 0 7 3 25 25]It's true that he's been helping us in our battles, but—![n][w][e]

[msg MSG_007_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 12 0 0]What? No...[n][w][e]

[msg MSG_007_3_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 13 0 0]Oh, um... These are Koromaru-san's old friends.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 14 0 0][f 4 23 0 7 3 25 25]They doubt our intentions regarding Koromaru-san, since he's been more frequently injured lately.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 15 0 0]How can we make them understand?[n][w][e]

[sel SEL_008_0_0 top]
[f 2 1]Just try explaining.[e]
[f 2 1]I don't think we can.[e]

[msg MSG_009_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 16 0 0]This is all a misunderstanding, everyone![n][w][e]

[msg MSG_010_0_0 [Black Shiba Inu]]
[f 2 1][vp 1 0 0 17 0 0]Grrrrr...[n][w][e]

[msg MSG_011_0_0 [Brown Cat]]
[f 2 1][vp 1 0 0 18 0 0]Hissss...![n][w][e]

[msg MSG_012_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 19 0 0]Please, don't be angry... Just calm down.[n][w][e]

[msg MSG_013_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 20 0 0]Ah![n][w][e]

[msg MSG_014_0_0 [Black Shiba Inu]]
[f 2 1][vp 1 0 0 21 0 0]*yelp*[n][w][e]

[msg MSG_015_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 22 0 0]Ah...[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 23 0 0]I'm so sorry. My hand is hard...[n][w][e]

[msg MSG_016_0_0 [Black Shiba Inu]]
[f 2 1][vp 1 0 0 24 0 0]*whine*[n][w][e]

[msg MSG_017_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 25 0 0]I see...[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 26 0 0]No wonder they're suspicious of me; my body is completely unnatural to them.[n][w][e]

[msg MSG_017_3_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 27 0 0]I hope that dog isn't hurt...[n][w][e]

[msg MSG_018_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 0 0 0 28 0 0]......[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 29 0 0]I've... been thinking lately.[n][w][e]

[msg MSG_018_3_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 30 0 0]No matter how human my heart becomes, my body will always remain a machine...[n][w][e]

[msg MSG_018_5_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 31 0 0]Of course, it's obvious when you think about it...[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 32 0 0]But I'm not strong enough to be a weapon, and I'm too stiff to pass as a human.[n][w][e]

[msg MSG_018_6_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 33 0 0]There's nowhere I truly belong... I'm neither completely machine, nor quite human...[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 0 0 0 34 0 0]......[n][w][e]

[sel SEL_019_0_0 top]
[f 2 1]Maybe so.[e]
[f 2 1]That's not true.[e] *

[msg MSG_020_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 35 0 0]My newfound emotions are something I should be happy about...[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 36 0 0]But, sometimes... I find myself wishing I could just be an unfeeling machine...[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 37 0 0]I know I'm not making sense...[n][w][e]

[msg MSG_021_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 38 0 0]But...![n][w][e]

[msg MSG_021_3_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 0 0 0 39 0 0]......[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 40 0 0]Oh... I'm sorry, [nf]-san.[n][w][e]

[msg MSG_021_5_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 41 0 0][f 5 13 22 5 7]Thank you.[n][w][e]

[msg MSG_021_7_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 42 0 0]You're right... Even if I can't quite explain it, I have to be true to myself.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 0 0 0 43 0 0][f 4 23 0 7 0 25 25]......[n][w][e]

[msg MSG_022_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 44 0 0]Sorry for bringing all of this up.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 45 0 0][f 4 23 0 7 3 25 25]If I hadn't been created, I never would have met everyone... And that includes you.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 46 0 0]If I can stay by your side, then nothing should faze me. I know that, but...[n][w][e]

[msg MND_023_0_0]
[f 2 1]I can sense Aigis's faint affection...[n][w][e]

[msg MSG_024_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 47 0 0]I should make sure that Koromaru-san's friends understand our situation.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 48 0 0][f 4 23 0 7 3 25 25]I don't want you to end up in danger again, [nf]-san.[n][w][e]

[msg MSG_024_3_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 49 0 0]I'll see you later... Excuse me.[n][w][e]

[msg MND_025_0_0]
[f 2 1]I parted ways with Aigis and[n]went back to the dorm.[n][w][e]

