[msg MSG_000_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 1 0 0]Regarding the incident from the other day with the cigarette butt in the boys' bathroom...[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 2 0 0]It seems the teachers want the student expelled as soon as we find out who it is.[n][w][e]

[msg MSG_001_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 4 65535 65535 0 0][vp 1 0 0 3 0 0]What?[n][w][e]

[msg MSG_002_0_0 [(SE) Secretary]]
[f 2 1][vp 1 0 0 4 0 0]Well, I guess we should've expected that.[n][w][e]

[msg MSG_003_0_0 [(SE) Vice President]]
[f 2 1][vp 1 0 0 5 0 0]It does hurt the school's reputation.[n][w][e]

[msg MSG_004_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 3 65535 65535 0 0][vp 1 0 0 6 0 0]I'll keep everyone posted on this. That's all for now.[n][w][e]

[msg MSG_005_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 3 65535 65535 0 0][vp 1 0 0 7 0 0]Expulsion, huh...[n][w][e]

[msg MSG_006_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 8 0 0]So what do you think about all of this?[n][w][e]
[f 2 1][bup 102 3 65535 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 1 3 25 25]About the smoker's punishment, I mean.[n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]It seems reasonable.[e]
[f 2 1]It seems too harsh.[e] *

[msg MSG_008_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 3 65535 65535 0 0][vp 1 0 0 10 0 0]I think... it's a little too harsh.[n][w][e]

[msg MSG_009_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 3 65535 65535 0 0][vp 1 0 0 11 0 0]Once I catch the culprit, I'll give him a good talking-to. The goal here should be to prevent this from happening again.[n][w][e]
[f 2 1][bup 102 3 65535 65535 0 0][vp 1 0 0 12 0 0]I'm not counting on it, but it'd be great if I could get people like him to change their ways.[n][w][e]

[msg MSG_010_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 3 65535 65535 0 0][vp 1 0 0 13 0 0][f 5 13 5 15 102]Yes, I think so, too.[n][w][e]

[msg MSG_011_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 3 65535 65535 0 0][vp 1 0 0 14 0 0]Once I catch the culprit, I'll give him a good talking-to. The goal here should be to prevent this from happening again.[n][w][e]
[f 2 1][bup 102 3 65535 65535 0 0][vp 1 0 0 15 0 0]I'm not counting on it, but it'd be great if I could get people like him to change their ways.[n][w][e]

[msg MSG_012_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 3 65535 65535 0 0][vp 1 0 0 16 0 0]I don't sympathize with students who break the rules, but...[n][w][e]
[f 2 1][bup 102 3 65535 65535 0 0][vp 1 0 0 17 0 0]Does kicking the "bad" kids out really make the school a better place?[n][w][e]

[msg MSG_013_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 3 65535 65535 0 0][vp 1 0 0 18 0 0]It's really not like me to whine about it. I guess I'm just confused because I feel so powerless.[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 19 0 0][f 4 23 0 1 0 25 25]If I can go above and beyond this time and earn the teacher's trust, my word will hold more weight around here.[n][w][e]

[msg MSG_013_5_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 20 0 0]Just you watch, [nl]-kun. I'll work my way to the top.[n][w][e]

[msg MND_014_0_0]
[f 2 1]Odagiri really opened up to me.[n][w][e]
[f 2 1]I feel like we're becoming better friends.[n][w][e]

[msg MSG_015_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 21 0 0]I still have some work left to do. I need to compile a list of suspects.[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 22 0 0]You can head on out of here. And take care.[n][w][e]

[msg MND_016_0_0]
[f 2 1]I left the student council room[n]and went back to the dorm.[n][w][e]

