[msg MSG_000_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 1 0 0]I'm sorry to drag you up here, but I wanted to tell you something.[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 2 0 0]The cigarette butt incident is going to be dropped. It seems interrogating every student in the school raised a few concerns.[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 3 0 0]I wanted to be student council president next year, and that teacher promised to endorse me if I agreed to help him.[n][w][e]

[msg MSG_000_5_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 3 65535 65535 0 0][vp 1 0 0 4 0 0]But I lost any hope of achieving that when I spoke up against him, not to mention the student body isn't so fond of me.[n][w][e]
[f 2 1][bup 102 3 65535 65535 0 0][vp 1 0 0 5 0 0]I rambled on about rules and fairness, but all I really proved was that I was desperate for power.[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Don't blame yourself.[e] *
[f 2 1]What matters is you realized it.[e]

[msg MSG_002_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 0 0 0 6 0 0][f 5 13 5 15 102]......[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 7 0 0]Now I understand why the president asked you to join the student council.[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 8 0 0]You aren't just feeding me sympathy or empty words. You genuinely mean what you say.[n][w][e]

[msg MSG_003_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 9 0 0][f 5 13 5 15 102]I see...[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 10 0 0]Now I understand why the president asked you to join the student council.[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 11 0 0]You don't say things to put people down. You're just honest with them.[n][w][e]

[msg MSG_004_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 10 65535 65535 0 0][vp 1 0 0 12 0 0]The system only works if you have people's trust, and trust isn't something you can force on anyone.[n][w][e]

[msg MSG_005_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 2 65535 65535 0 0][vp 1 0 0 13 0 0]When that teacher doubted you, I felt backed into a corner by a fool who simply had more power than I did.[n][w][e]
[f 2 1][bup 102 2 65535 65535 0 0][vp 1 0 0 14 0 0]I felt like the truth was being distorted and that I might lose a friend as a consequence.[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 1 0 25 25]If it wasn't for you, I would've become a tyrant. So thank you.[n][w][e]

[msg MND_006_0_0]
[f 2 1]Odagiri seems truly grateful.[n][w][e]
[f 2 1]I feel like we're becoming better friends.[n][w][e]

[msg MSG_007_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 3 65535 65535 0 0][vp 1 0 0 16 0 0]Don't you dare repeat what I just said to anyone.[n][w][e]
[f 2 1][bup 102 3 65535 65535 0 0][vp 1 0 0 17 0 0]I realize it's out of my usual character. And I'm sure everyone would just make fun of me.[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 18 0 0][f 4 23 0 1 0 25 25]J-Just promise, okay? I'll see you later.[n][w][e]

[msg MND_008_0_0]
[f 2 1]I parted ways with Odagiri[n]and went back to the dorm.[n][w][e]

