[msg MSG_000_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 1 0 0]Was that a cat's meow...?[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 2 0 0]Could it be—!?[n][w][e]

[msg MSG_001_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 3 0 0]Are you... Mii-chan-san?[n][w][e]

[msg MSG_002_0_0 [White Cat]]
[f 2 1][vp 1 0 0 4 0 0]Meow.[n][w][e]

[msg MSG_003_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 5 0 0]It is Mii-chan-san! I'm so glad...![n][w][e]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 6 0 0][nf]-san, let's go tell the old lady about this![n][w][e]

