[msg MSG_000_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 1 0 0]Sorry you went out of your way to stop by, but it was a quick meeting. Everyone left already.[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 2 0 0]It's nice not having those hyenas around.[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]You're not going home yet?[e]
[f 2 1]"It's nice"?[e]

[msg MSG_002_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 3 0 0]There's something I want to take care of before I go home.[n][w][e]

[msg MSG_003_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 3 65535 65535 0 0][vp 1 0 0 4 0 0]It's that cigarette butt in the boys' bathroom. I have to hurry and narrow down my suspects.[n][w][e]

[msg MSG_004_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 5 0 0]I see the way they look at me.[n][w][e]

[msg MSG_005_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 3 65535 65535 0 0][vp 1 0 0 6 0 0]Anyway, it's that cigarette butt in the boys' bathroom. I've been trying to narrow down my potential suspects.[n][w][e]

[msg MSG_006_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 7 0 0]So as you can see, we can't exactly hold a meeting right now. You can leave if you want.[n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]But I just got here...[e] *
[f 2 1]I think I'll stick around.[e] *

[msg MSG_008_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 8 0 0][f 5 13 5 15 102]I see...[n][w][e]

[msg MSG_009_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 9 0 0]If you're not in a hurry, can you spare a few minutes? I'd like to share something.[n][w][e]
[f 2 1][bup 102 3 65535 65535 0 0][vp 0 0 0 10 0 0][f 4 23 0 1 3 25 25]......[n][w][e]

[msg MSG_010_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 11 0 0][f 5 13 5 5 102]You're probably busy all the time, too. Try taking a break once in a while.[n][w][e]

[msg MSG_011_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 12 0 0]If you're not in a hurry, can you spare a few minutes? I'd like to share something.[n][w][e]
[f 2 1][bup 102 3 65535 65535 0 0][vp 0 0 0 13 0 0][f 4 23 0 1 3 25 25]Um...[n][w][e]

[msg MSG_012_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 14 0 0]A man without position, honor, or education... What does he cling to as he struggles through life?[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 15 0 0]"Sincerity," a man once told me.[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 16 0 0]Do you want to know what happened to that man?[n][w][e]

[msg MSG_012_5_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 17 0 0]Well, a TV anchorwoman was injured on the job while reporting on a story.[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 18 0 0]The TV station executives deemed it an "unfortunate accident."[n][w][e]

[msg MSG_012_6_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 2 65535 65535 0 0][vp 1 0 0 19 0 0]But when a magazine caught wind that they were hiding something, the execs threw the writer under the bus.[n][w][e]
[f 2 1][bup 102 2 65535 65535 0 0][vp 1 0 0 20 0 0]They said it was the writer who covered up the truth. They turned him into a scapegoat.[n][w][e]

[msg MSG_012_8_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 3 65535 65535 0 0][vp 1 0 0 21 0 0]And now that man is blacklisted from the TV industry, his life's calling. The same man who taught me the meaning of sincerity...[n][w][e]

[msg MSG_013_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 2 65535 65535 0 0][vp 1 0 0 22 0 0]In today's society, the weak are preyed upon by the strong. You can't survive on sincerity alone![n][w][e]
[f 2 1][bup 102 2 65535 65535 0 0][vp 1 0 0 23 0 0]As for me, [nl]-kun, I want to lead an organization that fosters strength.[n][w][e]
[f 2 1][bup 102 2 65535 65535 0 0][vp 1 0 0 24 0 0]And to do that, order is essential if I want to keep those with power in check.[n][w][e]

[msg MND_014_0_0]
[f 2 1]Odagiri spoke with passion.[n]His words seem truly heartfelt.[n][w][e]
[f 2 1]I feel like we're becoming better friends.[n][w][e]

[msg MSG_015_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 25 0 0]Well, that seems like a good spot to call it a day. Shall we head out together?[n][w][e]

[msg MND_016_0_0]
[f 2 1]I walked part of the way[n]home with Odagiri.[n][w][e]

