[msg MSG_000_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 2 65535 65535 0 0][vp 1 0 0 1 0 0]How many times do I have to explain it? It's like I'm talking to a moron.[n][w][e]

[msg MSG_001_0_0 [Vice President]]
[f 2 1][vp 1 0 0 2 0 0][f 5 21 0 1001]Why would you even accuse me!? The cigarette butt was in the boys' bathroom, right?[n][w][e]

[msg MSG_002_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 2 65535 65535 0 0][vp 1 0 0 3 0 0]Then can you prove it wasn't a girl who brought it and left it there?[n][w][e]

[msg MSG_003_0_0 [Secretary]]
[f 2 1][vp 1 0 0 4 0 0][f 5 21 0 1002]With that logic, this is never gonna end![n][w][e]
[f 2 1][vp 1 0 0 5 0 0][f 5 21 0 1002]I'm done with this. You're on your own.[n][w][e]

[msg MSG_004_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 2 65535 65535 0 0][vp 1 0 0 6 0 0]...Bunch of neanderthals.[n][w][e]

[sel SEL_005_0_0 top]
[f 2 1]They're the worst.[e] *
[f 2 1]You shouldn't accuse everyone.[e]

[msg MSG_006_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 7 0 0][f 5 13 5 15 102]Try not to hold it against them. They think like children—they just can't help it.[n][w][e]

[msg MSG_007_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 1 65535 65535 0 0][vp 1 0 0 8 0 0]Sooner or later, they'll see the light. Then I'll earn their trust, and they'll learn to respect me.[n][w][e]

[msg MSG_008_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 2 65535 65535 0 0][vp 1 0 0 9 0 0]I hope you're not just giving into peer pressure, [nl]-kun.[n][w][e]

[msg MSG_009_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 2 65535 65535 0 0][vp 1 0 0 10 0 0]Don't you see? A well-oiled machine is only as strong as its weakest cog![n][w][e]

[msg MSG_010_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 2 65535 65535 0 0][vp 1 0 0 11 0 0]I don't mean to isolate myself. I'm just remaining detached. Someone always gets hurt in any relationship sooner or later.[n][w][e]

[msg MSG_010_5_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 3 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 1 3 25 25]...I suppose I've gone on long enough. I apologize.[n][w][e]

[msg MND_011_0_0]
[f 2 1]Odagiri seems embarrassed...[n][w][e]
[f 2 1]I feel like I understand[n]him a little better now.[n][w][e]

[msg MSG_012_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 13 0 0]No point in having a meeting today if no one else is here. Let's go.[n][w][e]

[msg MND_013_0_0]
[f 2 1]I parted ways with Odagiri[n]and went back to the dorm.[n][w][e]

