[msg MND_000_0_0]
[f 2 1]I spent some time working[n]with the student council.[n][w][e]
[f 2 1]The hours flew by as I[n]worked hard on my tasks.[n][w][e]

[msg MSG_001_0_0 [Secretary]]
[f 2 1][vp 1 0 0 1 0 0]Thanks for all your hard work today.[n][w][e]

[msg MSG_002_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 2 0 0]Well then, please excuse me.[n][w][e]

[msg MSG_003_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 3 0 0]Oh, can I borrow you for a moment, [nl]-kun?[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 4 0 0]I'd like to hear your opinion on something. It's nothing serious, but...[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 5 0 0]Some students think the school uniform should be abolished, and they're gathering supporters.[n][w][e]

[sel SEL_004_0_0 top]
[f 2 1]They've got a point.[e]
[f 2 1]Sounds like nonsense.[e] *

[msg MSG_005_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 2 65535 65535 0 0][vp 1 0 0 6 0 0]That's so irrational of you, [nl]-kun.[n][w][e]

[msg MSG_006_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 7 0 0]Uniforms serve a purpose. It's a basic lesson that teaches you to play by the rules.[n][w][e]
[f 2 1][bup 102 2 65535 65535 0 0][vp 1 0 0 8 0 0][f 4 23 0 1 2 25 25]These students that complain about uniforms think that they can be functional members of society? Laughable![n][w][e]

[msg MSG_007_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 1 65535 65535 0 0][vp 1 0 0 9 0 0][f 5 13 5 15 102]Yes, because it is nonsense.[n][w][e]

[msg MSG_008_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 10 0 0]They think freedom is a life without rules. It's ridiculous, plain and simple.[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 11 0 0]Without rules, the whole system will collapse. They're mistaking selfishness for freedom.[n][w][e]

[msg MSG_009_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 3 65535 65535 0 0][vp 1 0 0 12 0 0]Sorry, overreacted a bit there.[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 13 0 0][f 4 23 0 1 0 25 25]I hate people with no common sense. I have very little desire to talk to them.[n][w][e]
[f 2 1][bup 102 1 65535 65535 0 0][vp 1 0 0 14 0 0][f 4 23 0 1 1 25 25]And don't take that the wrong way. I just want you to understand where I'm coming from.[n][w][e]

[msg MND_010_0_0]
[f 2 1]I think Odagiri's starting to trust me.[n][w][e]
[f 2 1]I feel like we're becoming better friends.[n][w][e]

[msg SYS_011_0_0]
[f 2 1]DEV: Unused label.[n][w][e]

[msg MSG_012_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 15 0 0]Why don't you head on home? I'll lock up here when I'm finished.[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 16 0 0]Get home safely.[n][w][e]

[msg MND_013_0_0]
[f 2 1]I left the student council room[n]and went back to the dorm.[n][w][e]

