[msg MSG_000_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 1 0 0]The battery and tire pressure look good... And I've already changed the oil, so that's fine.[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Impressive.[e]
[f 2 1]Looks like fun.[e] *

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 2 0 0][f 5 13 4 5 5]Well, this is just basic maintenance. Anyone could do the same.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 3 0 0][f 4 23 0 1 1 25 25]Though if I start tinkering with the suspension and whatnot, there'd be no end to it.[n][w][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 4 0 0][f 5 13 4 5 5]Indeed—maintaining and customizing a motorcycle is almost as enjoyable as riding it.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 5 0 0][f 4 23 0 1 1 25 25]Though if I start tinkering with the suspension and whatnot, there'd be no end to it.[n][w][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 6 0 0]There have been days I've lost track of time doing this, and had to run into meetings covered in oil...[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 1 1 25 25]It seems I'm the type of person who can fall very deep into things. I'll have to be more careful.[n][w][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 8 0 0]Oh, by the way—the matter involving my ex-fiancé was resolved sooner than I expected.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 9 0 0]They ended up reaching out to us about a potential business arrangement. Without any of the marriage talks, of course.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 10 0 0]We managed to negotiate some favorable terms, so that should put the company back on track.[n][w][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 11 0 0]I could have decided to burn that bridge, but I'd prefer not to shut down a genuine attempt to compromise.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 1 1 25 25]It may be thanks to you that I've become so open-minded.[n][w][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 13 0 0]All right, before we head out... I had a small gift for you, since you've done so much for me.[n][w][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 14 0 0]It's the key to my motorcycle.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 15 0 0]I'm not going to run from my future anymore. Rather... there's no longer any need to.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 16 0 0]This motorcycle isn't meant to be an escape from my feelings.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 17 0 0][f 4 23 0 1 1 25 25]It's a dear friend that gives me the freedom to go wherever I please.[n][w][e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 18 0 0]Once I realized that, I felt that I absolutely had to show it to you.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 19 0 0]As our leader, I think it would be quite fitting if you had the skill to ride my dear friend here.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 20 0 0]When this is all over, let's take this motorcycle and go on a trip somewhere together.[n][w][e]

[sel SEL_010_0_0 top]
[f 2 1]Great idea.[e]
[f 2 1]If I feel like it.[e]
[f 2 1]I don't have a license.[e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 21 0 0][f 5 13 4 10 5]Isn't it? We'll have to start thinking about where we want to go.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 22 0 0]I look forward to the day you learn how to ride it yourself.[n][w][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 23 0 0]Heh, no rush. Let me know when the mood strikes you.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 24 0 0][f 4 23 0 1 0 25 25]I'll be thinking about where we should go in the meantime, and I won't let life get in the way of it.[n][w][e]

[msg MSG_013_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 25 0 0]Heh, I'm sure you won't have any trouble getting one.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 26 0 0]I can even coach you, if you'd like. I'm fairly confident in my skills.[n][w][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 27 0 0]Once we go on that trip, I imagine it'll be full of things I've still yet to see.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 28 0 0][f 4 23 0 1 1 25 25]You were the one who taught me the joy of new discoveries. I can hardly wait.[n][w][e]

[msg MND_015_0_0]
[f 2 1]Mitsuru seems to respect me[n]deeply as a friend she can trust...[n][w][e]

[msg SYS_016_0_0]
[f 2 1]The Empress Social Link reached its maximum level! You can now fuse [clr 35]Alilat[clr 27], the ancient goddess![n][w][e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 29 0 0]All right, I think we've talked enough. Today, it's my turn to show you something new.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 30 0 0]Go ahead and sit on the back.[n][w][e]

[msg MSG_018_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 31 0 0]Don't worry, it's just a short drive. I even prepared a helmet for you.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 32 0 0]The weather is perfect today... The view from the Moonlight Bridge is quite a sight to see, you know.[n][w][e]

[msg MSG_019_0_0 [Mitsuru Kirijo]]
[f 2 1][vp 1 0 0 33 0 0]Here goes. Hold on tight![n][w][e]

[msg MND_021_0_0]
[f 2 1]We rode around the city, then[n]returned to the dorm...[n][w][e]

