[msg MSG_000_0_0 [Shady Student]]
[f 2 1][vp 1 0 0 1 0 0][f 5 21 0 1001]You hear me!? I wanna see evidence, smart guy![n][w][e]

[msg MSG_001_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 2 65535 65535 0 0][vp 1 0 0 2 0 0]I don't need evidence. I already know everything about you.[n][w][e]
[f 2 1][bup 102 2 65535 65535 0 0][vp 1 0 0 3 0 0]Like how you were arrested for beating up that guy in the park who snitched on you, right?[n][w][e]

[msg MSG_002_0_0 [Bemused Student]]
[f 2 1][vp 1 0 0 4 0 0][f 5 21 0 1002]Whoa! He's still at it? This is the third time today.[n][w][e]

[msg MSG_003_0_0 [Amused Student]]
[f 2 1][vp 1 0 0 5 0 0][f 5 21 0 1003]My boyfriend was so pissed after he was accused. This guy's really asking for it.[n][w][e]

[msg MSG_004_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 6 0 0]Keeping quiet will only make things worse for you.[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 7 0 0]If it's really not you, then give me some names.[n][w][e]

[msg MSG_004_3_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 8 0 0]And don't worry, I won't tell anyone. You have my word as a member of the disciplinary committee.[n][w][e]

[msg MSG_005_0_0 [Shady Student]]
[f 2 1][vp 1 0 0 9 0 0][f 5 21 0 1001]Better fuck off, asshole...[n][w][e]

[msg MND_006_0_0]
[f 2 1]This guy looks like he's[n]about to hit Odagiri![n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]Knock it off![e]
[f 2 1]......[e]

[msg MSG_008_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 31 65535 65535 0 0][vp 1 0 0 10 0 0]Ngh...[n][w][e]

[msg MSG_009_0_0 [Shady Student]]
[f 2 1][vp 1 0 0 11 0 0][f 5 21 0 1001]God, what a shitty day.[n][w][e]

[msg MSG_010_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 31 65535 65535 0 0][vp 1 0 0 12 0 0]Tch... Don't think I'll just let you get away with that![n][w][e]

[msg MSG_011_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 30 65535 65535 0 0][vp 1 0 0 13 0 0]Oh, hey, [nl]-kun.[n][w][e]
[f 2 1][bup 102 30 65535 65535 0 0][vp 1 0 0 14 0 0]What is it? Did you need something from me?[n][w][e]

[sel SEL_012_0_0 top]
[f 2 1]You went a little overboard.[e]
[f 2 1]Looks like you're hard at work.[e] *

[msg MSG_013_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 30 65535 65535 0 0][vp 1 0 0 15 0 0]You think so?[n][w][e]

[msg MSG_014_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 31 65535 65535 0 0][vp 1 0 0 16 0 0]Some people will lie and stab you in the back without hesitation if it benefits them.[n][w][e]
[f 2 1][bup 102 31 65535 65535 0 0][vp 1 0 0 17 0 0]People like that are a menace to society. Should we tolerate that kind of behavior? No, we should do something about it.[n][w][e]

[msg MSG_015_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 30 65535 65535 0 0][vp 1 0 0 18 0 0][f 5 13 5 15 102]You bet I am.[n][w][e]

[msg MSG_016_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 30 65535 65535 0 0][vp 1 0 0 19 0 0]If we turn a blind eye here, there's no stopping this from happening again.[n][w][e]
[f 2 1][bup 102 30 65535 65535 0 0][vp 1 0 0 20 0 0]And once it spirals out of control, there'll be nothing we can do. We should nip this problem in the bud while we still can.[n][w][e]

[msg MSG_017_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 32 65535 65535 0 0][vp 1 0 0 21 0 0]...I know what people think of me.[n][w][e]
[f 2 1][bup 102 32 65535 65535 0 0][vp 1 0 0 22 0 0]Then again, those who fight for justice have always butted heads with others. History speaks for itself.[n][w][e]

[msg MSG_017_5_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 30 65535 65535 0 0][vp 1 0 0 23 0 0][f 4 23 0 1 0 25 25]So let my actions serve as a warning to other offenders. A sensible person like you should understand, right?[n][w][e]

[msg MND_018_0_0]
[f 2 1]Seems like Odagiri's starting to trust me.[n][w][e]
[f 2 1]I feel like we're becoming better friends.[n][w][e]

[msg MSG_019_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 30 65535 65535 0 0][vp 1 0 0 24 0 0]I'm going to keep at it for now. You should head home before it gets dark.[n][w][e]

[msg MND_020_0_0]
[f 2 1]I parted ways with Odagiri[n]and went back to the dorm.[n][w][e]

