[msg MSG_000_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 1 0 0]Interesting... So this "takoyaki" doesn't contain an entire octopus, but only a small portion.[n][w][e]

[msg MSG_000_1_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 4 65535 65535 0 0][vp 1 0 0 2 0 0]I mean, that does make sense... The entire creature would be far too large for a single person.[n][w][e]

[msg MSG_000_2_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 3 0 0]Sometimes my own ignorance truly astounds me...[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Want me to treat you?[e]
[f 2 1]Why not give it a try?[e] *

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 4 0 0]Heh, who do you think I am?[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 5 0 0]Please, allow me to be the one to treat you.[n][w][e]

[msg MSG_002_5_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 4 65535 65535 0 0][vp 1 0 0 6 0 0]...What? They don't accept credit cards!?[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 0 0 0 7 0 0][f 4 23 0 1 0 25 25]......[n][w][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 8 0 0][f 5 13 4 5 5]Seeing is believing, I suppose...[n][w][e]

[msg MSG_003_5_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 9 0 0]Excuse me, um... One piece of takoyaki, please.[n][w][e]

[msg MSG_003_7_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 4 65535 65535 0 0][vp 1 0 0 10 0 0]...What? O-Oh, they're only sold in multiples?[n][w][e]

[msg MSG_003_8_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 11 0 0]How generous... So I'll receive an entire tray for this price...[n][w][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 12 0 0]So it's filled with diced octopus... Interesting.[n][w][e]

[msg MSG_004_1_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 13 0 0]Mmm... There's a mild sourness, combined with the chewy texture of the seafood... Quite flavorful.[n][w][e]

[msg MSG_004_2_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 4 65535 65535 0 0][vp 1 0 0 14 0 0]...Hm? Are there other ingredients mixed in?[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 5 1 25 25]In any case, it's quite good. C'est très bon![n][w][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 16 0 0]That reminds me, Akihiko once mentioned this place.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 0 0 0 17 0 0]......[n][w][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 18 0 0]Speaking of Akihiko... Don't you think he's been acting differently lately?[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 19 0 0]I can't place my finger on it, but I've known him for quite a long time... It feels like something's changed.[n][w][e]

[msg MSG_006_2_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 20 0 0]Maybe he's just maturing...[n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]Are you sad?[e]
[f 2 1]Are you happy?[e] *

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 21 0 0][f 5 13 4 5 5]Why would I be sad? I'm glad to see he's finally growing up.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 22 0 0]You're reading too much into it.[n][w][e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 23 0 0][f 5 13 4 15 5]Of course I'm happy.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 24 0 0][f 4 23 0 5 0 25 25]With all that we've been through, it can be difficult to get over what's happened in the past...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 25 0 0]But Akihiko is using his experiences to make himself stronger.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 26 0 0]I'm quite impressed by that.[n][w][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 27 0 0]When I look at Akihiko, I can't help but reflect upon my own life.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 28 0 0][f 4 23 0 5 1 25 25]It's the most peculiar feeling.[n][w][e]

[sel SEL_011_0_0 top]
[f 2 1]Maybe you're in love.[e]
[f 2 1]Maybe you're anxious.[e]
[f 2 1]It must be sadness.[e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 29 0 0]"In love"...? No, it's not that.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 30 0 0][f 5 13 4 5 5]Is that how it looks to you? I didn't realize.[n][w][e]

[msg MSG_013_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 31 0 0]He's just a friend... Or should I say, teammate? It's a bit hard to describe.[n][w][e]

[msg MSG_013_1_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 32 0 0]In any case, that is the extent of our relationship.[n][w][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 33 0 0][f 5 13 4 5 5]"Anxious"...? Hm, you may be right.[n][w][e]

[msg MSG_015_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 34 0 0]Maybe a part of me is panicking because I feel like I'm being left behind...[n][w][e]

[msg MSG_015_1_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 35 0 0]...Sorry, don't mind me.[n][w][e]

[msg MSG_016_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 36 0 0][f 5 13 4 5 5]As graduation day approaches, I do find myself feeling melancholy now and then...[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 37 0 0][f 4 23 0 5 1 25 25]Heh, I suppose this is something a second-year can't relate to just yet.[n][w][e]

[msg MND_017_0_0]
[f 2 1]Mitsuru seems to have a lot on her mind.[n][w][e]
[f 2 1]I feel like our relationship has grown...[n][w][e]

[msg MSG_018_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 38 0 0]I don't even know what I'm talking about.[n][w][e]

[msg MSG_018_1_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 39 0 0]Sorry to subject you to my thoughtless rambling. Just forget I said anything.[n][w][e]

[sel SEL_019_0_0 top]
[f 2 1]I'm rooting for you.[e]
[f 2 1]I heard nothing.[e] *

[msg MSG_020_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 40 0 0]Hm? I'm not sure what you mean.[n][w][e]

[msg MSG_021_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 41 0 0][f 5 13 4 5 5]Thank you.[n][w][e]

[msg MSG_022_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 42 0 0]That takoyaki was absolutely delicious. We should eat here again sometime.[n][w][e]

[msg MND_023_0_0]
[f 2 1]I decided to go back to the dorm...[n][w][e]

