[msg MSG_000_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 1 0 0]...Which is what I believe to be the proper way to wear one's uniform. Please keep these things in consideration.[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 2 0 0]I'm not saying everyone should follow this to the letter, so we'll leave it to the discretion of the individual.[n][w][e]

[msg MSG_001_0_0 [Secretary]]
[f 2 1][vp 1 0 0 3 0 0][f 5 21 0 1]Holy crap, did that just come out of his mouth?[n][w][e]

[msg MSG_002_0_0 [Vice President]]
[f 2 1][vp 1 0 0 4 0 0][f 5 21 0 2]I think this is the first time he's cared about anyone else's opinions.[n][w][e]

[msg MSG_003_0_0 [Council Liaison]]
[f 2 1][vp 1 0 0 5 0 0][f 5 21 0 3]Well, at least he's trying.[n][w][e]

[msg MSG_004_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 6 0 0]Thank you, [nl]-kun. I couldn't have done it without you.[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 7 0 0]So, how did I do? What'd everyone think?[n][w][e]

[sel SEL_005_0_0 top]
[f 2 1]Not too shabby.[e] *
[f 2 1]You were great.[e]

[msg MSG_006_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 1 65535 65535 0 0][vp 1 0 0 8 0 0][f 5 13 5 15 102]I'm proud of myself for making an effort at the very least.[n][w][e]

[msg MSG_007_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 9 0 0][f 5 13 5 5 102]Thanks, hearing that takes a huge weight off my shoulders.[n][w][e]

[msg MSG_008_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 10 0 0]I may have painted a selfish, arrogant portrait of myself to everyone, so I'll have to win back their trust.[n][w][e]

[msg MSG_009_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 11 0 0]Here, look at this.[n][w][e]

[msg MSG_010_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 12 0 0]One of the guys fessed up about the cigarette butt in the boys' bathroom.[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 13 0 0]It took a lot of persuasion, but he promised me he'll never smoke again.[n][w][e]

[msg MSG_010_5_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 14 0 0]This lighter is proof of that.[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 15 0 0]I earned his trust by showing compassion for others, just like you taught me.[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 16 0 0]That's why you should be the one to have it.[n][w][e]

[sel SEL_011_0_0 top]
[f 2 1]I'll cherish it.[e] *
[f 2 1]I guess I'll take it.[e] *

[msg MSG_012_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 1 65535 65535 0 0][vp 1 0 0 17 0 0][f 5 13 5 15 102]Thanks.[n][w][e]

[msg MSG_013_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 1 65535 65535 0 0][vp 1 0 0 18 0 0][f 5 13 5 15 102]Please do.[n][w][e]

[msg MND_014_0_0]
[f 2 1]DEV: *Unused message label. [n][f 1 5 0]*If this appears, it is a bug.[n][w][e]

[msg MSG_015_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 19 0 0]I've spent my whole life looking down on others. Such baseless bravado...[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 20 0 0]But you taught me an important lesson, something I'll carry with me forever.[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 21 0 0]I don't think I'll ever be anything like you, though.[n][w][e]

[msg MND_016_0_0]
[f 2 1]Odagiri seems embarrassed.[n][w][e]
[f 2 1]I feel an unbreakable bond with Odagiri.[n][w][e]

[msg SYS_017_0_0]
[f 2 1]The Emperor Social Link reached its maximum level! You can now fuse [clr 35]Odin[clr 27], the storm god![n][w][e]

[msg MSG_018_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 22 0 0]Do you remember the story I told you about the TV station's writer?[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 23 0 0]That man... He's my father.[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 24 0 0]I see now that sincerity is important, and I'm proud of myself for understanding that. I also realized what an amazing man my father is.[n][w][e]

[msg MSG_018_5_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 25 0 0]It's about time to go.[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 26 0 0]Say, [nl]-kun. Do you want to stop by somewhere before we head home?[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 27 0 0]Now that I think about it, we've never hung out outside of school before.[n][w][e]

[msg MND_019_0_0]
[f 2 1]I walked home with Odagiri,[n]who was in a great mood.[n][w][e]

