[msg MSG_000_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 1 0 0]I'm so nervous for some reason...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 2 0 0]The others are here in the dorm too... I hope no one finds out I snuck you into my room.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 3 0 0]They'll hear me if I'm too loud...[n][w][e]

[msg MSG_000_5_0 [Yukari Takeba]]
[f 2 1][cut 2 4 0][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 4 0 0]...![n][w][e]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 5 0 0]Wait, I didn't mean it like that! Don't get the wrong idea, okay!?[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]Too late.[e]
[f 2 1]I didn't say anything.[e]

[msg MSG_003_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 1 0][vp 1 0 0 6 0 0][f 5 13 7 15 2]H-Hey! You don't need to say it! Geez...[n][w][e]
[f 2 1][bup 2 2 65535 65535 1 0][vp 1 0 0 7 0 0][f 4 23 0 2 2 25 25]Whatever![n][w][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 8 0 0][f 5 13 7 5 2]A-Ah, right... Nothing at all.[n][w][e]
[f 2 1][bup 2 6 65535 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 2 6 25 25]...Am I always this crazy?[n][w][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 10 0 0]Oh, right... I wanted to give you something.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 11 0 0]This is for you.[n][w][e]

[msg MND_006_0_0]
[f 2 1]NOT USED[n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 12 0 0]You know what it is, right? It's the strap from my cell phone.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 13 0 0]I got it at the opening ceremony for the Moonlight Bridge.[n][w][e]

[msg MSG_007_3_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 14 0 0]It's been my special keepsake for years now...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 15 0 0]Because my dad bought it for me.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 0 0 0 16 0 0]......[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 17 0 0]I used to talk to the little charm attached to it when I was alone in my room.[n][w][e]

[msg MSG_007_5_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 18 0 0]Haha... You must think I'm nuts, huh?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 19 0 0]But ever since I got to know you, I've stopped talking to it.[n][w][e]

[msg MSG_007_7_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 20 0 0]Um, it means a lot to me, so I should explain why I'm giving it to you...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 21 0 0][f 4 23 0 2 3 25 25]I'm only gonna say this once, okay?[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 0 0 0 22 0 0]......[n][w][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 1 0][vp 1 0 0 23 0 0]I... I love you.[n][w][e]
[f 2 1][bup 2 1 65535 65535 1 0][vp 0 0 0 24 0 0]......[n][w][e]
[f 2 1][bup 2 4 65535 65535 1 0][vp 1 0 0 25 0 0][f 4 23 0 2 4 25 25]Th-That's it![n][w][e]

[msg MND_009_0_0]
[f 2 1]Yukari has professed her love for me,[n]and seems to want mine in return...[n][w][e]

[msg SYS_010_0_0]
[f 2 1]The Lovers Social Link reached its maximum level! You can now fuse [clr 35]Cybele[clr 27], the earth mother![n][w][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 26 0 0]Hey, when this is all over... Maybe we can spend some time together, just the two of us.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 27 0 0]I-In fact... would it be all right if I jumped the gun a bit, and... took some of that time right now?[n][w][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 28 0 0]I'm not ready to say goodnight yet.[n][w][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 1 0][vp 1 0 0 29 0 0]I-I'm blushing, aren't I...?[n][w][e]

[msg MND_014_0_0]
[f 2 1]I shared a special evening with Yukari.[n][w][e]

