[msg MSG_000_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 1 0 0]Oh...[n][w][e]

[msg MSG_000_3_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 2 0 0]You're Kiyoshi-san's grandmother. Good afternoon.[n][w][e]

[msg MSG_001_0_0 [Mii-chan's Owner]]
[f 2 1][vp 1 0 0 3 0 0][f 5 21 0 2]Oh, you're those nice students from before. Hello there![n][w][e]
[f 2 1][vp 1 0 0 4 0 0][f 5 21 0 2]You have great timing, I was just hoping to run into you two again.[n][w][e]
[f 2 1][vp 1 0 0 5 0 0][f 5 21 0 2]The truth is... Mii-chan's disappeared again.[n][w][e]

[msg MSG_002_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 6 0 0]Oh, so it's a recurring problem.[n][w][e]

[msg MSG_002_1_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 7 0 0]Don't worry, though. At least this time, we have an idea of where to find her.[n][w][e]

[msg MSG_003_0_0 [Mii-chan's Owner]]
[f 2 1][vp 1 0 0 8 0 0][f 5 21 0 2]No... That's all right.[n][w][e]
[f 2 1][vp 1 0 0 9 0 0][f 5 21 0 2]I believe that this time, Mii-chan went in search of something.[n][w][e]

[msg MSG_004_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 10 0 0]In search of something?[n][w][e]

[msg MSG_005_0_0 [Mii-chan's Owner]]
[f 2 1][vp 1 0 0 11 0 0][f 5 21 0 2]When cats feel that their life is nearly over, they look for a place to wait for the end. Isn't that what they say?[n][w][e]

[msg MSG_006_0_0 [Aigis]]
[f 2 1][bup 7 8 65535 65535 0 0][vp 1 0 0 12 0 0]W-Wait! But what about—![n][w][e]

[msg MSG_007_0_0 [Mii-chan's Owner]]
[f 2 1][vp 1 0 0 13 0 0][f 5 21 0 2]It's okay. Mii-chan even came to say goodbye to me before she left.[n][w][e]
[f 2 1][vp 1 0 0 14 0 0][f 5 21 0 2]So... I don't think I'll need you to find her anymore.[n][w][e]

[msg MSG_008_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 15 0 0]Miss...[n][w][e]

[msg MSG_009_0_0 [Mii-chan's Owner]]
[f 2 1][vp 1 0 0 16 0 0][f 5 21 0 2]Besides, it's more or less the same for me. My day will eventually come, too...[n][w][e]
[f 2 1][vp 1 0 0 17 0 0][f 5 21 0 2]And when it does, I hope I can rest in peace, without making trouble for anyone else.[n][w][e]

[msg MSG_010_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 18 0 0]Ah...[n][w][e]

[msg MSG_011_0_0 [Mii-chan's Owner]]
[f 2 1][vp 1 0 0 19 0 0][f 5 21 0 2]Oh, I'm so sorry.[n][w][e]
[f 2 1][vp 1 0 0 20 0 0][f 5 21 0 2]But, I did want to make sure I thanked you two again.[n][w][e]

[msg MSG_012_0_0 [Mii-chan's Owner]]
[f 2 1][vp 1 0 0 21 0 0][f 5 21 0 2]It was nice to see you. Well, good day.[n][w][e]

[msg MSG_013_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 22 0 0]Wait![n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 23 0 0]Miss, um...[n][w][e]

[msg MSG_013_3_0 [Aigis]]
[f 2 1][bup 7 2 65535 65535 0 0][vp 1 0 0 24 0 0]You're not alone![n][w][e]
[f 2 1][bup 7 2 65535 65535 0 0][vp 1 0 0 25 0 0]I'm certain of it![n][w][e]

[msg MSG_014_0_0 [Mii-chan's Owner]]
[f 2 1][vp 0 0 0 26 0 0]......[n][w][e]
[f 2 1][vp 1 0 0 27 0 0][f 5 21 0 2]Yes... You're right.[n][w][e]
[f 2 1][vp 1 0 0 28 0 0][f 5 21 0 2]No one is ever truly alone. Not as long as they continue to live in this world.[n][w][e]

[msg MSG_014_3_0 [Mii-chan's Owner]]
[f 2 1][vp 1 0 0 29 0 0][f 5 21 0 2]See? I have the company of a fine young lady such as yourself![n][w][e]

[msg MSG_015_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 30 0 0]......[n][w][e]

[msg MSG_016_0_0 [Mii-chan's Owner]]
[f 2 1][vp 1 0 0 31 0 0][f 5 21 0 2]Bless you, dear girl. You have a kind heart.[n][w][e]

[msg MSG_016_1_0 [Mii-chan's Owner]]
[f 2 1][vp 1 0 0 32 0 0][f 5 21 0 2]See you later![n][w][e]

[msg MSG_017_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 33 0 0]Kiyoshi-san said that people live to be happy...[n][w][e]

[msg MSG_017_1_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 34 0 0]Was Mii-chan-san happy?[n][w][e]

[sel SEL_018_0_0 top]
[f 2 1]I think she was happy.[e]
[f 2 1]Who knows?[e]

[msg MSG_019_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 35 0 0]Was Mii-chan-san... grateful to have been born...?[n][w][e]

[sel SEL_020_0_0 top]
[f 2 1]I'm sure she was.[e]
[f 2 1]I'm not sure.[e]

[msg MSG_021_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 36 0 0]For what purpose... was Mii-chan-san born...?[n][w][e]

[sel SEL_022_0_0 top]
[f 2 1]No one can say.[e]
[f 2 1]I don't know.[e]

[msg MSG_023_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 37 0 0]Life...[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 38 0 0]Where does it originate? Where does it go...?[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 39 0 0]What reason does life have to exist?[n][w][e]

[msg MSG_024_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 40 0 0]Living means connecting with others, but all life eventually ends.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 41 0 0]Parting seems to be a natural and inevitable aspect of life.[n][w][e]

[msg MSG_024_3_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 42 0 0]An unavoidable end...[n][w][e]

[msg MSG_024_4_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 43 0 0]Life... is cruel...[n][w][e]

[msg MSG_025_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 44 0 0]I wonder... Will I, too, someday have to part with you forever?[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 0 0 0 45 0 0]......[n][w][e]

[msg MSG_026_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 46 0 0]I do want to live, but that's not the only thing![n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 47 0 0]I... It's not just about becoming more human, it's about you...[n][w][e]

[msg MSG_026_3_0 [Aigis]]
[f 2 1][bup 7 2 65535 65535 0 0][vp 1 0 0 48 0 0]Being with you...![n][w][e]

[msg MSG_027_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 49 0 0]What... What is this feeling!?[n][w][e]

[msg MSG_027_1_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 50 0 0]What... do I want to do?[n][w][e]

[msg MND_028_0_0]
[f 2 1]Aigis looks terribly confused...[n][w][e]
[f 2 1]It seems we've grown closer...[n][w][e]

[msg MSG_029_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 0 0 0 51 0 0]......[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 52 0 0]I'm sorry for getting upset...[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 53 0 0]I'm going to head back.[n][w][e]

[msg MND_030_0_0]
[f 2 1]I decided to go back to the dorm.[n][w][e]

