[msg MSG_000_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 1 0 0]I like this place. I can see the entire town from here.[n][w][e]

[msg MSG_001_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 2 0 0]The Moonlight Bridge is to the right, and over there is Paulownia Mall.[n][w][e]

[msg MSG_001_3_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 3 0 0]Oh, and did you know you can also see our dorm from here?[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 7 0 25 25]Back in Yakushima, where I'd been sleeping, the ocean waters were much clearer than they are here...[n][w][e]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 5 0 0][f 4 23 0 7 1 25 25]But, I prefer the view here.[n][w][e]

[msg MSG_002_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 0 0 0 6 0 0]......[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 7 0 0]Before I came here, I didn't even think about whether I liked the scenery or not...[n][w][e]

[msg MSG_003_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 8 0 0]What about you, [nf]-san? Do you... like it here?[n][w][e]

[sel SEL_004_0_0 top]
[f 2 1]I like it here.[e] *
[f 2 1]Not really.[e]
[f 2 1]I don't care.[e]

[msg MSG_005_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 9 0 0][f 5 13 22 15 7]I'm so glad to hear that![n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 0 0 0 10 0 0][f 4 23 0 7 0 25 25]......[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 11 0 0]Feeling the same way, watching the same scenery...[n][w][e]

[msg MSG_005_3_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 12 0 0]...It's nice.[n][w][e]

[msg MSG_006_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 13 0 0]Oh, I see...[n][w][e]

[msg MSG_006_3_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 14 0 0]It's true that many painful things have happened here...[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 0 0 0 15 0 0][f 4 23 0 7 3 25 25]......[n][w][e]

[msg MSG_007_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 16 0 0][f 4 23 0 7 3 25 25]Oh, I see...[n][w][e]

[msg MSG_008_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 17 0 0]I began to feel "emotions" towards various things that I hadn't felt before...[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 18 0 0][f 4 23 0 7 3 25 25]It's a little scary sometimes.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 0 0 0 19 0 0]......[n][w][e]

[msg MSG_008_3_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 20 0 0]But, if I can change by being with you...[n][w][e]

[msg MSG_009_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 21 0 0]Then, I want to cherish these feelings.[n][w][e]

[msg MND_010_0_0]
[f 2 1]Aigis revealed her resolve to me...[n][w][e]
[f 2 1]It seems we've grown closer...[n][w][e]

[msg MSG_011_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 22 0 0]Oh, I'm sorry to have gone on for so long...[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 23 0 0]It's still January, so the winds can get quite chilly up here.[n][w][e]

[msg MSG_011_3_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 24 0 0]It would be awful if you caught a cold.[n][w][e]

[msg MND_012_0_0]
[f 2 1]We decided to go back to the dorm.[n][w][e]

