[msg MSG_000_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 1 0 0]Isn't it interesting how the sunlight on a clear winter day seems stronger than it is during the summer?[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 2 0 0]Perhaps it's because the sun is lower in the sky, and you don't have to look up to see it.[n][w][e]

[msg MSG_000_3_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 3 0 0]I've gotten so used to this view... But no two times is it ever exactly the same.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 7 3 25 25]You could say the same thing about one's day to day.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 5 0 0]...And each life as well.[n][w][e]

[msg MSG_001_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 6 0 0]The Promised Day is almost here.[n][w][e]

[msg MSG_001_1_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 7 0 0]January 31st...[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]You're right.[e] *
[f 2 1]I hadn't noticed...[e]

[msg MSG_003_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 8 0 0][f 5 13 22 15 7]Whenever I come up here, I get lost in my thoughts.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 7 3 25 25]"I can't let it end like this..." "I want to protect it all." Thoughts like that.[n][w][e]

[msg MSG_004_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 10 0 0][f 5 13 22 5 7]If only I could be that calm.[n][w][e]

[msg MSG_005_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 11 0 0]Since last time... I've tried thinking things through more rationally.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 12 0 0]I thought about that old lady and Mii-chan-san... and Kiyoshi-san as well.[n][w][e]

[msg MSG_006_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 13 0 0]I wonder if Mii-chan-san was alone until the moment of her death...[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 14 0 0]Somewhere no one could find her...[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 15 0 0]I think... the old lady wanted to be there for her at the end.[n][w][e]

[msg MSG_007_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 16 0 0]To live means to be connected to other people, but life is finite. Farewells are unavoidable.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 17 0 0]It's sad to think about, but you and I will have to part one day as well.[n][w][e]

[msg MSG_007_3_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 18 0 0]And then... I'll never be able to see you again.[n][w][e]

[msg MSG_008_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 19 0 0]There are so many things in life I don't understand... It's filled with so much pain.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 20 0 0]You meet others, forge relationships, and spend time with them... and then they're gone, leaving you behind.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 21 0 0]Leaving you alone...[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 0 0 0 22 0 0]......[n][w][e]

[msg MSG_009_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 23 0 0]When I think about that, I just can't hold back my feelings.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 24 0 0][f 4 23 0 7 0 25 25]...But, I understand now.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 25 0 0]That's just how it is.[n][w][e]

[msg MSG_010_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 26 0 0]No two views are alike. No two days are the same.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 27 0 0]It's natural for everything to disappear, reemerge, and constantly change.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 28 0 0]Life is both short and finite.[n][w][e]

[msg MSG_010_3_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 29 0 0]That's what makes it so invaluable, and why one feels that it must be cherished...[n][w][e]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 30 0 0]When you think about it, it's a miracle that two given people are able to ever meet in this chaotic flow of time and space...[n][w][e]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 31 0 0]I believe that's why we find happiness in forging bonds and relationships with others.[n][w][e]

[msg MSG_010_5_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 32 0 0]And... that might be the true joy of being alive...[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 33 0 0][f 4 23 0 7 3 25 25]It can be sad, but at the same time so warm... Beautiful because it is destined to end...[n][w][e]

[msg MSG_010_6_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 34 0 0]And that's why... I mustn't hesitate any longer.[n][w][e]

[msg MSG_010_7_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 35 0 0]I need to tell you...[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 36 0 0]Even if this wish of mine is to never come true... I still want to tell you my true feelings...[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 0 0 0 37 0 0]......[n][w][e]

[msg MSG_011_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 1 0][vp 1 0 0 38 0 0][nf]-san...[n][w][e]
[f 2 1][bup 7 0 65535 65535 1 0][vp 1 0 0 39 0 0]I...[n][w][e]
[f 2 1][bup 7 0 65535 65535 1 0][vp 1 0 0 40 0 0]I love you...[n][w][e]

[msg MSG_012_0_0 [Aigis]]
[f 2 1][bup 7 8 65535 65535 1 0][vp 1 0 0 41 0 0]I know I'm a machine. I know... that I cannot truly touch you as a human.[n][w][e]

[msg MSG_012_2_0 [Aigis]]
[f 2 1][bup 7 8 65535 65535 1 0][vp 1 0 0 42 0 0]But I can't help it![n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 43 0 0][f 4 23 0 7 3 25 25]All I can see or think about is you, [nf]-san...[n][w][e]

[msg MND_013_0_0]
[f 2 1]I sense Aigis' strong affection towards me...[n][w][e]
[f 2 1]I'd better choose my words carefully...[n][w][e]

[msg MND_014_0_0]
[f 2 1]Come to think of it, [clr 2]I have a special[clr 27][n][clr 2]relationship with another person already[clr 27]...[n][w][e]

[msg MSG_015_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 1 0][vp 1 0 0 44 0 0]I love you so much... that I feel like I'm going to break down somehow...[n][w][e]

[sel SEL_016_0_0 top]
[f 2 1]I love you, too.[f 2 9 1 1 353][e] <3
[f 2 1]Sorry, but I can't...[e]

[msg MSG_017_0_0 [Aigis]]
[f 2 1][bup 7 2 65535 65535 1 0][vp 1 0 0 45 0 0]...![n][w][e]
[f 2 1][bup 7 0 65535 65535 1 0][vp 0 0 0 46 0 0][f 4 23 0 7 0 25 25]......[n][w][e]

[msg MSG_018_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 0 0 0 47 0 0]......[n][w][e]

[msg MSG_018_1_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 48 0 0]I-I'm sorry. I can't... think of anything to say...[n][w][e]

[msg MSG_018_2_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 49 0 0]Perhaps something really has broken inside of me...[n][w][e]

[msg MSG_018_3_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 1 0][vp 1 0 0 50 0 0]I feel... so happy...[n][w][e]
[f 2 1][bup 7 1 65535 65535 1 0][vp 0 0 0 51 0 0]......[n][w][e]

[msg MND_019_0_0]
[f 2 1]Aigis has expressed her feelings for me.[n][w][e]
[f 2 1]I have entered a special[n]relationship with Aigis...[n][w][e]

[msg MND_020_0_0]
[f 2 1]There's no going back now...[n][w][e]

[msg MSG_021_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 1 0][vp 1 0 0 52 0 0]Um... W-We should go back.[n][w][e]
[f 2 1][bup 7 1 65535 65535 1 0][vp 0 0 0 53 0 0]......[n][w][e]

[msg MSG_021_3_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 1 0][vp 1 0 0 54 0 0]I-I'll go ahead. I... It's too difficult to look you in the eye right now.[n][w][e]

[msg MSG_021_4_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 1 0][vp 1 0 0 55 0 0]Um...[n][w][e]
[f 2 1][bup 7 1 65535 65535 1 0][vp 1 0 0 56 0 0][f 4 23 0 7 1 25 25]S-See you later...[n][w][e]

[msg MND_022_0_0]
[f 2 1]We decided to go back[n]to the dorm separately.[n][w][e]

[msg MSG_023_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 57 0 0]...![n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 0 0 0 58 0 0]......[n][w][e]

[msg MSG_024_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 59 0 0]...Yes, I expected as much.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 60 0 0]I-I'm sorry. I can't... think of anything to say...[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 61 0 0]Perhaps something really has broken inside of me...[n][w][e]

[msg MSG_024_3_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 62 0 0]I thought being able to tell you my feelings would have been enough for me...[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 63 0 0]But, it's only made me want to be with you more... I'm hopeless, aren't I?[n][w][e]

[msg MND_025_0_0]
[f 2 1]Aigis expressed her feelings for me.[n][w][e]
[f 2 1]It seems we've grown closer...[n][w][e]

[msg MSG_026_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 64 0 0]Thank you, [nf]-san.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 65 0 0]I'm grateful that you gave me a straight answer, and that you treated me like a human being.[n][w][e]

[msg MSG_026_3_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 66 0 0]...It's painful. But now, I feel like I can move on without regrets.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 0 0 0 67 0 0][f 4 23 0 7 3 25 25]......[n][w][e]

[msg MSG_026_5_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 68 0 0]Oh, um... Shall we head back?[n][w][e]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 69 0 0][f 4 23 0 7 1 25 25]And if you don't mind, I'd like to be as we always have. As a friend by your side.[n][w][e]

[msg MND_027_0_0]
[f 2 1]I decided to go back to the dorm with Aigis.[n][w][e]

