[msg MSG_000_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 1 0 0]I think I've acquired a taste for fast food.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 2 0 0]Just the other day, I had the urge to ride my motorcycle out at night to buy some.[n][w][e]

[msg MSG_000_3_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 3 0 0]Heh... It's your fault that I'm having these temptations now, you know.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 0 0 0 4 0 0][f 4 23 0 1 0 25 25]......[n][w][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 5 0 0]Do you remember when I told you I was hesitant to meet up with you like this?[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 6 0 0]I'd like it if you could forget I ever said that.[n][w][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 7 0 0]We both sleep under the same roof—there's no point in stressing over it.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 8 0 0]And besides...[n][w][e]

[msg MSG_002_3_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 6 65535 65535 0 0][vp 1 0 0 9 0 0]I just need to steel my resolve.[n][w][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 10 0 0]Say, [nl]. I have just one favor to ask.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 11 0 0][f 4 23 0 1 1 25 25]Could you continue to show me new places like this? Just until graduation.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 1 0 25 25]I'd like to see more of this world that I've been so blind to.[n][w][e]

[msg MSG_006_3_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 13 0 0]Or... is that too selfish a request?[n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]I don't mind at all.[e] *
[f 2 1]Is that all you need?[e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 14 0 0][f 5 13 4 15 5]...Thank you, [nl].[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 15 0 0]Let's make some wonderful memories with what little time we have left.[n][w][e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 16 0 0][f 5 13 4 5 5]Well...[n][w][e]

[msg MSG_009_1_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 17 0 0]...No, this is fine. This is the decision I've made.[n][w][e]

[msg MSG_009_2_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 18 0 0]I'd like to focus on enjoying what little time we have left.[n][w][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 19 0 0]You've taught me so many new things.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 20 0 0]Whether you're taking command in battle, or just talking with me like this...[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 21 0 0][f 4 23 0 1 1 25 25]As long as I have these memories of you, I'll be all right.[n][w][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 22 0 0]...Or so I hope.[n][w][e]

[msg MND_013_0_0]
[f 2 1]I can sense Mitsuru's resolve.[n][w][e]
[f 2 1]Our relationship has grown...[n][w][e]

[msg MSG_015_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 23 0 0]Now then, the day is still young.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 24 0 0]You promised me your time. I'd like you to make good on that now.[n][w][e]

[msg MND_016_0_0]
[f 2 1]I hung out with Mitsuru until it[n]was time to return to the dorm.[n][w][e]

