[msg MSG_000_0_0 [Mii-chan's Owner]]
[f 2 1][vp 1 0 0 1 0 0][f 5 21 0 1701]Awww, there, there... You seem a little skinnier than you used to be.[n][w][e]
[f 2 1][vp 1 0 0 2 0 0][f 5 21 0 1701]This little one is all I have left to keep me company...[n][w][e]

[msg MSG_000_3_0 [Mii-chan's Owner]]
[f 2 1][vp 1 0 0 3 0 0][f 5 21 0 1701]I was so lonely when Mii-chan was missing... I don't know how I can thank the both of you.[n][w][e]

[msg MSG_001_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 4 0 0]Lonely...[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 5 0 0][f 4 23 0 7 0 25 25]Is being by oneself... lonely?[n][w][e]

[msg MSG_002_0_0 [Mii-chan's Owner]]
[f 2 1][vp 1 0 0 6 0 0][f 5 21 0 1701]Oh yes, dear.[n][w][e]
[f 2 1][vp 1 0 0 7 0 0][f 5 21 0 1701]When you get to be my age, you'll find that all the wealth in the world won't take care of you.[n][w][e]
[f 2 1][vp 1 0 0 8 0 0][f 5 21 0 1701]No one can truly live alone.[n][w][e]
[f 2 1][vp 1 0 0 9 0 0][f 5 21 0 1701]Some of my neighbors have delightful children, but... they aren't interested in old ladies like me.[n][w][e]

[msg MSG_003_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 10 0 0]Miss...[n][w][e]

[msg MSG_004_0_0 [Mii-chan's Owner]]
[f 2 1][vp 1 0 0 11 0 0][f 5 21 0 1701]Well, Mii-chan, shall we go home?[n][w][e]

[msg MSG_004_5_0 [Mii-chan's Owner]]
[f 2 1][vp 1 0 0 12 0 0][f 5 21 0 1701]Thank you so much, you two.[n][w][e]

[msg MSG_005_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 13 0 0]It seems that living is something that can't be done alone.[n][w][e]

[sel SEL_006_0_0 top]
[f 2 1]You might be right.[e] *
[f 2 1]That's not true.[e]
[f 2 1]I don't know.[e]

[msg MSG_007_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 14 0 0][f 5 13 22 15 7]Yes.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 15 0 0]It's important to keep someone in your thoughts, and to know that you are in theirs.[n][w][e]

[msg MSG_007_3_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 16 0 0]To be able to contact them anytime...[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 17 0 0]And... to touch them...[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 0 0 0 18 0 0]......[n][w][e]

[msg MSG_008_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 19 0 0][f 5 13 22 5 7]It isn't?[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 20 0 0][f 4 23 0 7 0 25 25]But I learned everything I know about living from you, [nf]-san...[n][w][e]

[msg MSG_008_3_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 21 0 0]It's a very difficult matter.[n][w][e]

[msg MSG_009_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 22 0 0][f 5 13 22 5 7]To live means to spend time around people...[n][w][e]

[msg MSG_009_1_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 23 0 0]To keep someone in your thoughts, and know that you are in theirs... To be able to contact them anytime...[n][w][e]

[msg MSG_009_3_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 24 0 0]And... to touch them...[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 0 0 0 25 0 0]......[n][w][e]

[msg MSG_010_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 26 0 0]But, I do understand one thing.[n][w][e]

[msg MSG_010_1_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 27 0 0]It seems I feel happy when I'm together with you, [nf]-san.[n][w][e]

[msg MND_011_0_0]
[f 2 1]Aigis is smiling shyly...[n][w][e]
[f 2 1]It seems we've grown closer...[n][w][e]

[msg MSG_012_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 28 0 0]But, I have to wonder...[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 29 0 0]If living means to be able to connect with other people...[n][w][e]

[msg MSG_012_3_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 30 0 0]How close to that goal can I come with a body like mine?[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 0 0 0 31 0 0]......[n][w][e]

[msg MSG_013_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 32 0 0]...Just kidding.[n][w][e]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 33 0 0][f 4 23 0 7 1 25 25]I've been exceedingly negative lately. I wonder what's wrong with me...[n][w][e]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 34 0 0][f 4 23 0 7 1 25 25]We should start heading back.[n][w][e]

[msg MND_014_0_0]
[f 2 1]We decided to go back to the dorm.[n][w][e]

