[msg MSG_000_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 1 0 0]Go on and have a seat.[n][w][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 2 0 0]Um... I know what you're thinking.[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]This room is... Wow.[e]
[f 2 1]No fair.[e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 3 0 0]Yukari always tells me it's like having a second lounge.[n][w][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 4 0 0]Haha, my apologies. I admit, it's a tad excessive.[n][w][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 5 0 0]Our maid staff assisted with the furnishings... That's the reason it looks like this.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 6 0 0]Although... maybe I shouldn't be making excuses.[n][w][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 7 0 0]Up until now, I held strong to the idea that I must live by the honor of the Kirijo name.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 8 0 0]But despite how occupied I should have been with the family business, I always found time to spend with you.[n][w][e]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 1 3 25 25]It made me realize I'd been running away this whole time... Running from the truth of what I really wanted.[n][w][e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 10 0 0]Now that the engagement's broken off, it's been complete chaos around me.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 11 0 0]But I know we can make it through this.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 12 0 0]Some are calling me a spoiled brat who's ruining everything... But beyond that are many others showing their support.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 13 0 0]It's been a much-needed reminder that I'm not alone.[n][w][e]

[sel SEL_009_0_0 top]
[f 2 1]That's a relief.[e]
[f 2 1]Never let go of that.[e]
[f 2 1]This is your strength.[e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 14 0 0][f 5 13 4 15 5]Right... I apologize for worrying you. I couldn't have done this without you paving the way.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 15 0 0]Allow me to thank you on behalf of the Group. I'm certain my father would feel the same way.[n][w][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 16 0 0][f 5 13 4 5 5]I won't. It's those people who are my strength... and the strength of the Kirijo family.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 17 0 0]I never would have realized this if I didn't have you as a friend.[n][w][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 18 0 0][f 5 13 4 5 5]No... I gained that strength thanks to you.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 19 0 0]If you hadn't opened my eyes, I very well could have turned out as contemptible as my ex-fiancé.[n][w][e]

[msg MSG_013_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 20 0 0]Ever since we met, my life has been full of new experiences.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 21 0 0]You're always showing me sides of this world that I've never seen before.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 22 0 0][f 4 23 0 1 0 25 25]The memories we've made—fighting side-by-side, exploring the city, or even just passing the hours talking—I'll treasure them forever.[n][w][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 23 0 0]Treating you to a cup of tea here is hardly going to repay you for everything you've done for me.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 24 0 0]But think of it as my pledge to give you my full support from now on.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 25 0 0]I'll do whatever I can to make sure that happens.[n][w][e]

[msg MND_015_0_0]
[f 2 1]Mitsuru's gratitude and resolve is clear...[n][w][e]
[f 2 1]I feel like our relationship has grown...[n][w][e]

[msg MSG_016_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 26 0 0]All right, I'm going to call Yukari and the others. Settle down and make yourself comfortable.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 27 0 0][f 4 23 0 1 1 25 25]I should warn you, there's no telling how long we can talk over tea and snacks. I hope you're prepared.[n][w][e]

[msg MND_017_0_0]
[f 2 1]We all chatted as the hours flew by...[n][w][e]

