[msg MSG_000_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 1 0 0]Interesting... So this is what the interior looks like...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 2 0 0]It's smaller than I expected.[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Is this your first time?[e]
[f 2 1]Do you know how to eat it?[e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 3 0 0]Well, technically, yes. But I did pass by once with Akihiko...[n][w][e]

[msg MSG_002_1_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 4 0 0]So... I understand that you don't eat with utensils here?[n][w][e]

[msg MSG_002_2_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 6 65535 65535 0 0][vp 1 0 0 5 0 0]My lack of knowledge on this subject is a serious problem.[n][w][e]

[msg MSG_002_3_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 6 0 0][f 4 23 0 1 0 25 25][f 5 13 4 5 5]In all honesty, it's a good thing you're here.[n][w][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 7 0 0]O-Of course, don't be ridiculous.[n][w][e]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 8 0 0][f 4 23 0 1 3 25 25]...Or so I'd like to say, but truthfully, I'm not that familiar.[n][w][e]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 1 3 25 25]I saw a commercial for fast food once, but I didn't expect that picking it up with bare hands was the norm...[n][w][e]

[msg MSG_003_3_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 6 65535 65535 0 0][vp 1 0 0 10 0 0]Just goes to show how out of touch I am.[n][w][e]

[msg MSG_003_4_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 11 0 0][f 4 23 0 1 3 25 25]My lack of knowledge on this subject is a serious problem.[n][w][e]

[msg MSG_003_5_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 12 0 0][f 5 13 4 5 5]In all honesty, it's a good thing you're here.[n][w][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 13 0 0]Is it actually profitable to sell these items at such low prices?[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 14 0 0]I'd be interested to know the average cost per unit...[n][w][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 15 0 0]Oh, sorry. I found myself lost in thought again.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 16 0 0]In truth, I didn't ask you here just to eat...[n][w][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 17 0 0]I wanted to express my personal thanks to you.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 18 0 0]Right now, our strength and conviction are being tested to their limits.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 19 0 0]We've only made it this far because we've been blessed with each other's partnership.[n][w][e]

[msg MSG_006_3_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 20 0 0]I know I've been asking a lot of you—even more than the others. But I truly appreciate it.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 21 0 0][f 4 23 0 1 0 25 25]I just wanted to make sure you knew that.[n][w][e]

[msg MND_007_0_0]
[f 2 1]Mitsuru seems to trust me...[n][w][e]
[f 2 1]I feel like our relationship has grown...[n][w][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 22 0 0]Hm? Oh, I didn't realize we were talking for so long.[n][w][e]

[msg MSG_008_1_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 23 0 0]It would be rude to let the food grow cold. Shall we begin?[n][w][e]

[msg MND_009_0_0]
[f 2 1]I ate burgers with Mitsuru, then[n]headed back to the dorm.[n][w][e]

[msg SYS_010_0_0]
[f 2 1]DEV: Label is not used[n][w][e]

