[msg MSG_000_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 1 0 0]Sorry to drag you along on this personal venture.[n][w][e]

[msg MSG_000_1_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 0 0][vp 0 0 0 2 0 0]......[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Looking for something specific?[e] *
[f 2 1]Need some help?[e] *
[f 2 1]Borrowing a book?[e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 3 0 0][f 5 13 4 5 5]No, not exactly. But thank you.[n][w][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 4 0 0]Looking through the literature section made me realize something.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 5 0 0]There are so many books about romance, but far fewer on the domestic life that comes after it.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 6 0 0]I wonder if that means the most exciting time in one's life comes prior to the wedding...[n][w][e]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 1 3 25 25]Does everyone go into marriage with the expectation of losing something?[n][w][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 8 0 0][f 5 13 4 5 5]Hm? Oh, no. There's no need.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 1 1 25 25]Thank you, though.[n][w][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 10 0 0]Looking through the literature section made me realize something.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 11 0 0]There are so many books about romance, but far fewer on the domestic life that comes after it.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 12 0 0]I wonder if that means the most exciting time in one's life comes prior to the wedding...[n][w][e]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 13 0 0][f 4 23 0 1 3 25 25]Does everyone go into marriage with the expectation of losing something?[n][w][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 4 65535 65535 0 0][vp 1 0 0 14 0 0]...Hm? Oh, sorry.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 1 0 25 25]I was just a little distracted.[n][w][e]

[msg MSG_006_2_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 16 0 0]My mind was getting away from me... It's been happening quite often as of late.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 17 0 0][f 4 23 0 1 1 25 25]What a bad habit of mine. I should be more conscious of it.[n][w][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 18 0 0]The truth is, the Group is in turmoil over the inheritance issue.[n][w][e]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 19 0 0][f 4 23 0 1 3 25 25]And some of the older members are of the opinion that a student like me isn't up to the task...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 20 0 0][f 4 23 0 1 0 25 25]But... I'm the daughter of the head of the Group. I need to show that I can take the lead.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 21 0 0]...Even if I have to make sacrifices to do it.[n][w][e]

[sel SEL_009_0_0 top]
[f 2 1]Did something happen?[e]
[f 2 1]That doesn't sound good.[e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 22 0 0]A... fiancé has been chosen for me.[n][w][e]

[msg MSG_010_5_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 23 0 0]He's the new president of one of our affiliates, and he's much older than me...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 24 0 0]But if I agree to the marriage, the future of the company will be secured.[n][w][e]

[msg MSG_010_7_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 25 0 0]He's planning to announce the partnership and our engagement at the same time.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 26 0 0]Doing so will give the appearance that the company is stable both inside and out.[n][w][e]

[msg MSG_010_9_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 27 0 0]This is the best solution for everyone involved...[n][w][e]

[sel SEL_011_0_0 top]
[f 2 1]Is it really?[e]
[f 2 1]I didn't know...[e] *

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 28 0 0]This was decided a long time ago. It's just going to take place a bit sooner than originally planned, that's all.[n][w][e]

[msg MSG_012_1_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 29 0 0]This is... for the best...[n][w][e]

[msg MSG_013_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 30 0 0][f 5 13 4 5 5]Well, of course you didn't.[n][w][e]

[msg MSG_013_1_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 31 0 0]You're the only person I've told so far.[n][w][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 32 0 0]My mother and father walked the same path.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 33 0 0]So... I won't run from my fate.[n][w][e]

[sel SEL_015_0_0 top]
[f 2 1]Are you sure about this?[e]
[f 2 1]That's admirable.[e]
[f 2 1]I'll do something about it.[e] *

[msg MSG_016_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 34 0 0][f 5 13 4 5 5]Of course I am.[n][w][e]

[msg MSG_016_2_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 35 0 0]Think about it. What would I do if I broke off the engagement?[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 36 0 0]Leave everything behind and go on a journey of self-discovery?[n][w][e]

[msg MSG_016_4_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 0 0][vp 0 0 0 37 0 0]......[n][w][e]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 38 0 0]Why would you ask me that? You're making me doubt myself...[n][w][e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 39 0 0]I'm... glad to hear that you agree.[n][w][e]
[f 2 1][bup 5 3 65535 65535 0 0][vp 0 0 0 40 0 0][f 4 23 0 1 3 25 25]......[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 41 0 0][f 4 23 0 1 1 25 25]Yes... No matter what happens, I can't turn my back on the Kirijo name.[n][w][e]

[msg MSG_018_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 4 65535 65535 0 0][vp 0 0 0 42 0 0]...![n][w][e]
[f 2 1][bup 5 2 65535 65535 0 0][vp 1 0 0 43 0 0][f 4 23 0 1 2 25 25]You shouldn't make promises you can't keep. What could you possibly do?[n][w][e]

[msg MSG_018_3_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 44 0 0]Still, though...[n][w][e]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 45 0 0][f 5 13 4 15 5]Hearing you say that almost makes me want to believe.[n][w][e]

[msg MND_020_0_0]
[f 2 1]Mitsuru looks conflicted...[n][w][e]
[f 2 1]I feel like our relationship has grown...[n][w][e]

[msg MSG_021_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 46 0 0]...Say, [nl].[n][w][e]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 47 0 0]Recently, I've been feeling a little hesitant about meeting up with you like this.[n][w][e]

[msg MSG_021_3_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 48 0 0]I already made the decision to carry out my duty.[n][w][e]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 49 0 0]But... whenever I talk with you, my resolve begins to falter.[n][w][e]

[msg MSG_022_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 50 0 0]Why do I feel this way when I'm with you...?[n][w][e]
[f 2 1][bup 5 3 65535 65535 0 0][vp 0 0 0 51 0 0]......[n][w][e]

[msg MSG_023_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 52 0 0]...I think it would be best if we left off here for today.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 53 0 0]Sorry to do this after inviting you out here, but I need to head home and go over some paperwork on the partnership.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 54 0 0]Excuse me.[n][w][e]

[msg MND_024_0_0]
[f 2 1]After parting ways with Mitsuru,[n]I decided to return to the dorm.[n][w][e]

