[msg MSG_000_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 1 0 0]There's no trace of her.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 2 0 0]I can detect hostile readings like Shadows, but when it comes to this...[n][w][e]

[msg MSG_000_3_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 3 0 0]I'm useless... aren't I?[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 4 0 0]And I was the one who insisted we search... I'm sorry.[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Don't let it get to you.[e]
[f 2 1]We should head back for today.[e]
[f 2 1]Let's keep looking.[e]

[msg MSG_002_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 5 0 0]It's not working out, after all... How could a machine like myself have feelings like a normal person?[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 0 0 0 6 0 0]......[n][w][e]

[msg MSG_002_3_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 7 0 0]It's getting dark. We should probably give up the search for today.[n][w][e]

[msg MSG_002_5_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 8 0 0]Thank you very much, [nf]-san.[n][w][e]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 9 0 0]I'm happy that you took the time to indulge me in this.[n][w][e]

[msg MSG_003_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 10 0 0]Yes, you're right. It's getting dark.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 0 0 0 11 0 0]......[n][w][e]

[msg MSG_003_3_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 12 0 0]It's not working out, after all... How could a machine like myself have feelings like a normal person?[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 13 0 0]Thank you very much, [nf]-san.[n][w][e]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 14 0 0]I'm happy that you took the time to indulge me in this.[n][w][e]

[msg MSG_004_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 15 0 0]Thank you, [nf]-san.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 16 0 0]But it's getting dark. We should probably give up the search for today.[n][w][e]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 17 0 0]I'm happy that you took the time to indulge me in this.[n][w][e]

[msg MSG_004_3_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 0 0 0 18 0 0]......[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 19 0 0]It's not working out, after all... How could a machine like myself have feelings like a normal person?[n][w][e]

[msg MND_005_0_0]
[f 2 1]Aigis is smiling...[n][w][e]
[f 2 1]I feel like I understand[n]Aigis a little better now...[n][w][e]

[msg MSG_006_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 20 0 0]I'll be going back alone today... I need some time to think.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 21 0 0]I'm sorry... And after you invited me out, too...[n][w][e]

[msg MND_007_0_0]
[f 2 1]We decided to go back[n]to the dorm separately.[n][w][e]

