[msg MSG_000_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 1 0 0]Hey, can we go look at some earrings?[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 2 0 0]We didn't end up going last time, remember? I still need to check out what new pieces they have![n][w][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 3 0 0]Hm? It's that kid...[n][w][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 4 0 0]Hey, there.[n][w][e]

[msg MSG_003_0_0 [Child]]
[f 2 1][vp 1 0 0 5 0 0][f 5 21 0 1001]Mommy![n][w][e]

[msg MSG_004_0_0 [Child's Mother]]
[f 2 1][vp 1 0 0 6 0 0][f 5 21 0 1002]Oh, there you are! You need to stay by Mommy's side, okay?[n][w][e]

[msg MSG_005_0_0 [Child]]
[f 2 1][vp 1 0 0 7 0 0][f 5 21 0 1001]Okay![n][w][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 8 0 0]He was with his mother today, huh...[n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]That's a relief.[e]
[f 2 1]What's wrong?[e]

[msg MSG_008_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 9 0 0][f 5 13 7 5 2]Yeah. Kinda looked like he was lost again, so I was worried for a second there...[n][w][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 10 0 0]Nothing... I was just remembering something.[n][w][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 11 0 0]I've heard that no matter how careful you try to be, kids just love wandering off on their own...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 12 0 0]Especially when they're that young. Must be hard being a mother.[n][w][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 13 0 0]Anyway, you ready to go?[n][w][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 14 0 0]Hmm, none of the earrings caught my eye...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 15 0 0]Maybe I should find a new shop to check out. If I go on a day off, I could look somewhere a little further from home.[n][w][e]

[msg MSG_012_3_0 [Yukari Takeba]]
[f 2 1][bup 2 6 65535 65535 0 0][vp 1 0 0 16 0 0]But if I go out on my own again, who knows what creeps might come after me...? The news hasn't been very reassuring.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 17 0 0][f 4 23 0 2 0 25 25]Gee, what should I do? If only someone would come with me...[n][w][e]

[sel SEL_013_0_0 top]
[f 2 1]I'll go.[e]
[f 2 1]Good luck.[e]
[f 2 1]What's the magic word?[e]

[msg MSG_014_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 18 0 0][f 5 13 7 10 2]Hehe, thanks! I'll treat you to something when we get there.[n][w][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 19 0 0][f 5 13 7 5 2]Hey, take a hint![n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 20 0 0][f 4 23 0 2 0 25 25]Fine, I'll be blunt. Could you come with me? I'll treat you to something![n][w][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 65535 65535 0 0][vp 1 0 0 21 0 0][f 5 13 7 5 2]Uhh... Pleeeaaase?[n][w][e]
[f 2 1][bup 2 6 65535 65535 0 0][vp 0 0 0 22 0 0]......[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 23 0 0][f 4 23 0 2 1 25 25]Okay, sorry. I'll be real with you. I'd love it if you'd be able to come with me.[n][w][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 24 0 0]Haha, so much for being afraid to rely on others, huh? Now it just slips out.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 25 0 0][f 4 23 0 2 0 25 25]I'll have to learn to hold back, too.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 26 0 0]I can't ask for too much, but I shouldn't do everything by myself, either...[n][w][e]

[msg MSG_017_3_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 27 0 0]I guess it'll all balance out if you start relying on me more, too.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 28 0 0]At least, that's what I think.[n][w][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 29 0 0]Oh, right... I wanted to give you something.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 30 0 0]That's actually why I wanted to hang out today.[n][w][e]

[msg MND_019_0_0]
[f 2 1]DEV: *Unused message labels.  *If this appears, it is a bug.[n][w][e]

[msg MSG_020_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 31 0 0]You know what it is, right? It's the strap from my cell phone.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 32 0 0]I got it at the opening ceremony for the Moonlight Bridge.[n][w][e]

[msg MSG_020_3_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 33 0 0]It's been my special keepsake for many years...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 34 0 0]Because my dad bought it for me.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 35 0 0]I used to talk to the little charm attached to it when I was alone in my room.[n][w][e]

[msg MSG_020_5_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 36 0 0]Haha... You must think I'm nuts, huh?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 37 0 0][f 4 23 0 2 0 25 25]But it was pretty much the only thing that got me through.[n][w][e]

[msg MSG_021_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 38 0 0]I can honestly say I wouldn't be here today if it weren't for that little guy.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 39 0 0][f 4 23 0 2 1 25 25]So I was just thinking, maybe it could help you in some way too.[n][w][e]

[sel SEL_022_0_0 top]
[f 2 1]Can I really have this?[e]
[f 2 1]That's intense.[e]

[msg MSG_023_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 40 0 0]Yup. I'm doing better these days, so I'd like you to have it.[n][w][e]

[msg MSG_024_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 65535 65535 0 0][vp 1 0 0 41 0 0]Hey, don't look at me like that! Just accept the gesture, okay? Geez.[n][w][e]

[msg MND_025_0_0]
[f 2 1]I can feel the tight bond[n]between me and Yukari...[n][w][e]

[msg SYS_026_0_0]
[f 2 1]The Lovers Social Link reached its maximum level! You can now fuse [clr 35]Cybele[clr 27], the earth mother![n][w][e]

[msg MSG_027_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 42 0 0]Oh, right, so as we were saying... It'd be nice to go someplace a little further from home.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 43 0 0][f 4 23 0 2 1 25 25]We've talked about this before, remember? About going out to the mountains or something.[n][w][e]

[msg MSG_027_3_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 44 0 0]Let's make good on that, okay? We could even go to Destinyland![n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 45 0 0]I can't wait to make some more fun memories together![n][w][e]

[msg MSG_028_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 46 0 0]All right, well, now that that's decided, it's time to start planning![n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 47 0 0]Give some thought to where you'd like to go, okay?[n][w][e]

[msg MND_029_0_0]
[f 2 1]Yukari and I returned to the dorm.[n][w][e]

