[msg MSG_000_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 1 0 0]...And that concludes the disciplinary committee's forecast report.[n][w][e]

[msg MSG_001_0_0 [(SE) Vice President]]
[f 2 1][vp 1 0 0 2 0 0]Next up is the treasurer's report.[n][w][e]

[msg MSG_002_0_0 [(SE) Chihiro Fushimi]]
[f 2 1][vp 1 0 0 3 0 0]Yes.[n][w][e]

[msg MSG_003_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 4 0 0]Hey, sorry, but I was hoping you had some time once this meeting's over.[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 5 0 0]We can talk up on the roof.[n][w][e]

