[msg MSG_001_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 1 0 0]Um... I know what you want to say.[n][w][e]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 2 0 0][f 4 23 0 1 3 25 25]Our maid staff assisted with the furnishings. I recognize it's a bit beyond standard for a dorm room.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 3 0 0][f 4 23 0 1 1 25 25]It's almost like a second lounge, isn't it?[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 4 0 0]Haha, Yukari says that to me all the time...[n][w][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 5 0 0]Oh... I almost forgot.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 6 0 0]Here. I want you to have this.[n][w][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 7 0 0]It's the key to my motorcycle.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 8 0 0]I'm not going to run from my future anymore.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 1 1 25 25]Rather... there's no longer any need to.[n][w][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 10 0 0]I don't have to think of my motorcycle as a means of escaping my feelings.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 11 0 0][f 4 23 0 1 1 25 25]Though I do regret that I won't be riding it as often anymore...[n][w][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 12 0 0]I'd... rather ride with you.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 13 0 0][f 4 23 0 1 0 25 25]Of course, you'll have to sit on the back until you get your license...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 14 0 0]But when this is all over, I'll teach you how to ride yourself.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 1 1 25 25]I'll be looking forward to it.[n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]I'll give it a try.[e]
[f 2 1]I'm fine with the back.[e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 16 0 0][f 5 13 4 15 5]Please do, but remember to be careful.[n][w][e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 4 65535 65535 0 0][vp 1 0 0 17 0 0][f 5 13 4 5 5]Oh... Is that so? Well, if that's what you prefer, I suppose.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 0 0 0 18 0 0][f 4 23 0 1 1 25 25]......[n][w][e]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 19 0 0][f 4 23 0 1 3 25 25]Still... I'd like to be the one holding on to you now and then.[n][w][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 1 0][vp 0 0 0 20 0 0]......[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 21 0 0][f 4 23 0 1 1 25 25]It's... still a bit embarrassing to call you by your first name.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 22 0 0][f 4 23 0 1 0 25 25]But when we're alone, no one else can hear me.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 23 0 0]Your name... is more than just a name to me. It's something special.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 24 0 0]If I were in danger, it would be my last, desperate call for help.[n][w][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 1 0][vp 0 0 0 25 0 0]......[n][w][e]
[f 2 1][bup 5 0 65535 65535 1 0][vp 1 0 0 26 0 0]Right... So, um...[n][w][e]
[f 2 1][bup 5 3 65535 65535 1 0][vp 1 0 0 27 0 0][f 4 23 0 1 3 25 25][nf], I... I want to be with you tonight...[n][w][e]
[f 2 1][bup 5 0 65535 65535 1 0][vp 1 0 0 28 0 0][f 4 23 0 1 0 25 25]Will you... stay with me?[n][w][e]

[msg MND_012_0_0]
[f 2 1]Mitsuru has professed her love to me,[n]and seems to want mine in return...[n][w][e]

[msg SYS_013_0_0]
[f 2 1]The Empress Social Link reached its maximum level! You can now fuse [clr 35]Alilat[clr 27], the ancient goddess![n][w][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 1 0][vp 1 0 0 29 0 0]This... really is embarrassing...[n][w][e]

[msg MND_015_0_0]
[f 2 1]I shared a special evening with Mitsuru.[n][w][e]

