[msg MSG_000_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 1 0 0]It's so simple... You just purchase a ticket at the window, and then walk in to enjoy a film...[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 2 0 0][f 4 23 0 1 1 25 25]This may sound silly to you, but I've always wanted to try the whole theater experience.[n][w][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 3 0 0]Even though we sat at the end of the aisle, I didn't feel that my view was compromised in the least...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 4 0 0]It seems a lot of thought goes into the design and construction of a movie theater.[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]...Said the rich girl.[e]
[f 2 1]Glad you enjoyed it.[e] *

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 4 65535 65535 0 0][vp 1 0 0 5 0 0]H-Hey now. This was my first time having the freedom to choose my own seat—I'm simply impressed by the options.[n][w][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 6 0 0][f 5 13 4 15 5]It's thanks to you, [nl]. I've never felt comfortable enough to come here alone.[n][w][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 7 0 0]I'm sure most people don't consider this to be such a big deal...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 8 0 0][f 4 23 0 1 0 25 25]I imagine someone like Yukari would have no reservations seeing a movie by herself.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 9 0 0]She's likely more suited to riding a motorcycle than I am, as well.[n][w][e]

[sel SEL_006_0_0 top]
[f 2 1]A motorcycle?[e] *
[f 2 1]You're not suited?[e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 10 0 0][f 5 13 4 15 5]Yes, you must have seen it when I rode in to provide support for the team.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 11 0 0]However... that wasn't my original motivation for getting it.[n][w][e]

[msg MSG_007_3_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 12 0 0]With a motorcycle, I can go where I want, when I want, all on my own.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 13 0 0][f 4 23 0 1 1 25 25]You could say it's my modest attempt at rebellion against the many restrictions of my life.[n][w][e]

[msg MSG_007_5_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 14 0 0]After it was damaged, I considered letting go... But ultimately, I decided to have it repaired instead.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 1 1 25 25]I don't regret it. Even now, I spend my time tuning it whenever I can.[n][w][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 16 0 0][f 5 13 4 5 5]I don't quite mean to say that...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 17 0 0]It's just that my time available for riding is limited.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 18 0 0]Lately, I find myself dreaming about driving to some far-off destination without telling a soul...[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 19 0 0][f 4 23 0 1 1 25 25]Well, fantasizing can be fun in its own way.[n][w][e]

[sel SEL_009_0_0 top]
[f 2 1]What a high-class biker.[e]
[f 2 1]Let's go for a ride.[e] *

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 20 0 0][f 5 13 4 5 5]It sounds strange, doesn't it? Well, maybe it is.[n][w][e]

[msg MSG_010_1_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 21 0 0]Everyone is against me riding it. They think it's too dangerous.[n][w][e]

[msg MSG_010_2_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 22 0 0]Even so, I'm quite fond of it. Maybe you should give it a try yourself, if you're so inclined.[n][w][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 4 65535 65535 0 0][vp 1 0 0 23 0 0]Together...? Just the two of us?[n][w][e]

[msg MSG_012_3_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 24 0 0]Can you ride one on your own? Or do you plan to cling on behind me?[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 25 0 0][f 4 23 0 1 1 25 25][f 5 13 4 15 5]Heh... Whichever it is, you've got your work cut out for you.[n][w][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 26 0 0]In any case, you have my thanks. I'm feeling a lot better now.[n][w][e]

[msg MND_015_0_0]
[f 2 1]Mitsuru is expressing her appreciation.[n][w][e]
[f 2 1]I feel like our relationship has grown...[n][w][e]

[msg MSG_016_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 27 0 0]You know, I have to wonder...[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 28 0 0]When my parents went through stressful times, maybe they had moments like this too.[n][w][e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 29 0 0]Sorry, I know this isn't the proper place to stand around chatting.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 30 0 0]But if it's all right with you... why don't we stay here a bit longer before heading back?[n][w][e]

[msg MND_018_0_0]
[f 2 1]I passed some time with Mitsuru,[n]then headed back to the dorm.[n][w][e]

