[msg MSG_000_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 1 0 0]Isn't it interesting how the sunlight on a winter's day seems clearer than it is during the summer?[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 2 0 0]Maybe it's because the sun is lower in the sky, and you don't have to look up to see it.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 3 0 0]I've gotten so used to this view... But no two times is it ever exactly the same.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 4 0 0]You could say the same thing about one's day to day.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 5 0 0]...And each life as well.[n][w][e]

[msg MSG_001_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 6 0 0]The Promised Day is almost here.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 1 3 25 25]January 31st...[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]You're right.[e]
[f 2 1]I hadn't noticed...[e]

[msg MSG_003_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 8 0 0][f 5 13 22 15 7]Whenever I come up here, I get lost in my thoughts.[n][w][e]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 1 1 25 25]"I can't let it end like this..." "I want to protect it all." Thoughts like that.[n][w][e]

[msg MSG_004_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 10 0 0][f 4 23 0 1 1 25 25][f 5 13 22 5 7]If only I could be that calm.[n][w][e]

[msg MSG_005_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 11 0 0]Since last time... I've tried thinking things through more rationally.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 12 0 0]I thought about that old lady and Mii-chan-san... and Kiyoshi-san as well.[n][w][e]

[msg MSG_006_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 13 0 0]I wonder if Mii-chan-san was alone until the moment of her death...[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 14 0 0]Somewhere no one could find her...[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 15 0 0]I think... the old lady wanted to be there for her at the end.[n][w][e]

[msg MSG_007_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 16 0 0]To live means to be connected to other people, but life is finite. Farewells are unavoidable.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 17 0 0]It's sad to think about, but you and I will have to part one day as well.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 18 0 0][f 4 23 0 1 3 25 25]And then... I'll never be able to see you again.[n][w][e]

[msg MSG_008_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 19 0 0]There are so many things in life I don't understand... It's filled with so much pain.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 20 0 0]You meet others, forge relationships, and spend time with them... and then they're gone, leaving you behind.[n][w][e]
[f 2 1][bup 7 10 65535 65535 0 0][vp 1 0 0 21 0 0][f 4 23 0 1 10 25 25]Leaving you alone...[n][w][e]
[f 2 1][bup 7 10 65535 65535 0 0][vp 0 0 0 22 0 0][f 4 23 0 1 10 25 25]......[n][w][e]

[msg MSG_009_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 23 0 0]I... am a machine.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 24 0 0]No matter how human my heart becomes, my body will never be flesh and blood.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 25 0 0]As long as I undergo maintenance and can replace my broken parts, I will exist indefinitely.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 26 0 0][f 4 23 0 1 3 25 25]...But even so, I can understand this much.[n][w][e]

[msg MSG_010_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 27 0 0]No two views are alike. No two days are the same.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 28 0 0][f 4 23 0 1 3 25 25]It's natural for everything to disappear, reemerge, and constantly change.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 29 0 0][f 4 23 0 1 3 25 25]Life is both short and finite.[n][w][e]

[msg MSG_010_3_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 30 0 0]That's what makes it so invaluable, and why one feels that it must be cherished...[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 31 0 0][f 4 23 0 1 0 25 25]When you think about it, it's a miracle that two given people are able to ever meet in this chaotic flow of time and space...[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 32 0 0][f 4 23 0 1 0 25 25]That's why we find happiness in forging bonds and relationships.[n][w][e]

[msg MSG_010_5_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 33 0 0]I think that might be the true joy of being alive...[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 34 0 0]It can be sad, but at the same time so warm... Beautiful because it is destined to end...[n][w][e]

[msg MSG_010_7_0 [Aigis]]
[f 2 1][bup 7 2 65535 65535 0 0][vp 1 0 0 35 0 0]And that's why... I mustn't hesitate any longer.[n][w][e]
[f 2 1][bup 7 2 65535 65535 0 0][vp 1 0 0 36 0 0]I have to tell you my feelings...[n][w][e]

[msg MSG_011_0_0 [Aigis]]
[f 2 1][bup 7 2 65535 65535 0 0][vp 1 0 0 37 0 0]I want to spend time with you, [nf]-san.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 38 0 0][f 4 23 0 1 0 25 25]To see new sights with you... To go to new places together.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 39 0 0][f 4 23 0 1 0 25 25]To share new experiences... To make far more memories.[n][w][e]

[msg MSG_012_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 40 0 0]I know I'm being selfish.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 41 0 0]Your time is finite, and I know that someone like me shouldn't be taking it away from you...[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 42 0 0][f 4 23 0 1 0 25 25]But, even so... my wish is to be your closest friend.[n][w][e]

[sel SEL_013_0_0 top]
[f 2 1]You're already my best friend.[e]
[f 2 1]That's a beautiful wish.[e]

[msg MSG_014_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 43 0 0]...![n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 44 0 0][f 4 23 0 1 3 25 25]I... I'm sorry. I... don't know what to say...[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 45 0 0][f 4 23 0 1 3 25 25]I thought telling you how I felt would be enough for me...[n][w][e]

[msg MSG_014_3_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 46 0 0]But... hearing you say that makes me so happy.[n][w][e]
[f 2 1][bup 7 1 65535 65535 0 0][vp 0 0 0 47 0 0]......[n][w][e]

[msg MSG_015_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 48 0 0]...![n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 49 0 0]I... I'm sorry. I... don't know what to say...[n][w][e]

[msg MSG_015_3_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 50 0 0]I was so afraid of being nothing but a burden to you...[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 0 0 0 51 0 0]......[n][w][e]

[msg MSG_016_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 52 0 0]Thank you so much, [nf]-san.[n][w][e]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 53 0 0]I'll never forget the time we spent here today.[n][w][e]

[msg MSG_017_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 54 0 0]We should start heading back.[n][w][e]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 55 0 0]I wouldn't want my best friend to catch a cold from staying out too late.[n][w][e]

[msg MND_018_0_0]
[f 2 1]I decided to go back to the dorm with Aigis.[n][w][e]

