[msg MSG_000_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 1 0 0]So, [nl], um...[n][w][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 2 0 0]I need to know the etiquette of this place. Are there any customs I should follow?[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]Slurp the noodles.[e]
[f 2 1]Add a lot of toppings.[e]
[f 2 1]Don't let it get soggy.[e]
[f 2 1]Drink all the soup.[e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 3 0 0]Oh, r-right, slurping is considered polite! I've heard about that.[n][w][e]

[msg MSG_003_1_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 4 0 0]I hope I can do this correctly...[n][w][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 5 0 0]So we select the number of toppings ourselves? I see...[n][w][e]

[msg MSG_004_1_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 6 0 0]How interesting that they leave that to the discretion of the consumer.[n][w][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 4 65535 65535 0 0][vp 1 0 0 7 0 0]Oh! Understood. So it's important to eat quickly, then...[n][w][e]

[msg MSG_005_1_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 8 0 0][f 4 23 0 1 0 25 25]Sounds sensible. I imagine said eagerness shows respect to the chef, as well.[n][w][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 4 65535 65535 0 0][vp 1 0 0 9 0 0]A-All of it!? Does everyone do that...?[n][w][e]

[msg MSG_006_1_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 10 0 0][f 4 23 0 1 0 25 25]I... I'll do my best.[n][w][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 11 0 0]Now then... Let us begin.[n][w][e]

[msg MSG_007_1_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 12 0 0]Bon appetit![n][w][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 13 0 0]Hmm... What a fascinating flavor...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 14 0 0]I thought it strange at first, but it carries with it a subtle complexity.[n][w][e]

[msg MSG_008_3_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 1 1 25 25]...Yes, this is quite delicious.[n][w][e]

[msg MSG_008_5_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 16 0 0]Excuse me, Mr. Chef de Cuisine?[n][w][e]

[msg MSG_009_0_0 [Ramen Shop Owner]]
[f 2 1][vp 1 0 0 17 0 0][f 5 21 0 2]Chef de cuisine? You talkin' to me?[n][w][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 18 0 0]Your ramen is absolutely wonderful. It's been a while since I last gave my compliments to the chef.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 19 0 0][f 4 23 0 1 0 25 25]What do you use for the bouillon?[n][w][e]

[msg MSG_011_0_0 [Ramen Shop Owner]]
[f 2 1][vp 1 0 0 20 0 0][f 5 21 0 2]Bouillon...? What the hell is that?[n][w][e]

[msg MSG_011_1_0 [Ramen Shop Owner]]
[f 2 1][vp 1 0 0 21 0 0][f 5 21 0 2]If yer askin' about the recipe, sorry, miss. Can't tell ya.[n][w][e]

[msg MSG_011_2_0 [Ramen Shop Owner]]
[f 2 1][vp 1 0 0 22 0 0][f 5 21 0 2]That's how we put bread on the table.[n][w][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 23 0 0]So it's a secret recipe... I completely understand. You don't have to tell me.[n][w][e]

[msg MSG_012_1_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 24 0 0]You mentioned this dish puts bread on the table? I suppose that means it comes in sandwich form as well...[n][w][e]

[msg MSG_012_2_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 25 0 0]I see. What a fascinating delicacy.[n][w][e]

[msg MSG_013_0_0 [Ramen Shop Owner]]
[f 2 1][vp 1 0 0 26 0 0][f 5 21 0 2]Uh, that ain't exactly... Well, whatever.[n][w][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 27 0 0]The recipe of something this delectable could likely be patented and sold for quite a profit...[n][w][e]

[msg MSG_015_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 28 0 0]Oh, sorry, um... My imagination got the best of me.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 29 0 0]I'd been wanting to try ramen for a long time.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 0 0 0 30 0 0]......[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 31 0 0]Do you find that... unusual?[n][w][e]

[sel SEL_016_0_0 top]
[f 2 1]Very.[e]
[f 2 1]Not at all.[e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 32 0 0]I see...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 33 0 0]I would have been free to visit as I pleased, but...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 34 0 0]Dining alone is... rather awkward.[n][w][e]

[msg MSG_018_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 35 0 0]Oh, that's good to hear.[n][w][e]

[msg MSG_018_2_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 36 0 0]I never had the opportunity to eat this kind of food growing up...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 37 0 0]The style of restaurant is new to me, too.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 38 0 0]So I have to admit... it's something I've always wanted to try.[n][w][e]

[msg MSG_018_5_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 39 0 0][f 4 23 0 1 1 25 25]I'm glad we came here today. You've already taught me so much about ramen etiquette.[n][w][e]

[msg MSG_019_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 40 0 0]I would love to return here in the future.[n][w][e]

[msg MND_020_0_0]
[f 2 1]I saw an unexpected side of Mitsuru.[n][w][e]
[f 2 1]I feel like our relationship has grown...[n][w][e]

[msg MSG_021_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 41 0 0]Oh, I didn't notice the time.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 42 0 0]We should be going.[n][w][e]

[msg MND_022_0_0]
[f 2 1]We decided to go back to the dorm.[n][w][e]

