[msg MSG_000_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 1 0 0]You know, there's not much time left for us to spend like this...[n][w][e]

[msg MSG_000_1_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 2 0 0]In just a short while, we'll be looking back on these days with nostalgia.[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]What's next for you?[e]
[f 2 1]Did something happen?[e] *

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 3 0 0]Well...[n][w][e]
[f 2 1][bup 5 3 65535 65535 0 0][vp 0 0 0 4 0 0]......[n][w][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 5 0 0][f 5 13 4 5 5]No... I'm probably just tired. It's nothing you need to worry about.[n][w][e]
[f 2 1][bup 5 3 65535 65535 0 0][vp 0 0 0 6 0 0][f 4 23 0 1 3 25 25]......[n][w][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 7 0 0]Since my father passed away, I've been faced with a number of complicated issues.[n][w][e]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 8 0 0]My inheritance... the future of the Kirijo Group... and the expectations of everyone involved with both...[n][w][e]

[msg MSG_004_2_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 9 0 0]It's possible I won't be going to college or starting a career. I may need to walk a different path.[n][w][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 10 0 0]Say, [nl]...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 11 0 0]What does marriage mean to you?[n][w][e]

[sel SEL_006_0_0 top]
[f 2 1]It's all for love.[e] *
[f 2 1]It's a social agreement.[e]
[f 2 1]It's about compromise.[e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 12 0 0][f 5 13 4 15 5]Heh... That's a straightforward answer.[n][w][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 13 0 0]However, I'm a Kirijo. I can't let my feelings tug me around when making these decisions.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 14 0 0]An agreement between two parties—such as marriage—takes careful consideration.[n][w][e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 15 0 0]That's true.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 16 0 0]Marriage is a union in a social context as well... That's what differentiates it from simply dating.[n][w][e]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 17 0 0][f 4 23 0 1 3 25 25]Yes, I shouldn't have needed to ask you about that...[n][w][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 18 0 0]I don't know about that.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 19 0 0]Compromise is something that can only occur if both sides are willing.[n][w][e]

[msg MSG_010_2_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 20 0 0][f 4 23 0 1 1 25 25]Or are you speaking from experience?[n][w][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 21 0 0]My parents' marriage was arranged for strategic reasons.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 22 0 0]But, as time passed, they slowly grew to honestly love each other.[n][w][e]

[msg MSG_011_2_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 23 0 0]I don't think they were unhappy with their lives... Love can take many different forms.[n][w][e]

[msg MSG_011_3_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 24 0 0][f 4 23 0 1 3 25 25]Am I... wrong about this?[n][w][e]

[sel SEL_012_0_0 top]
[f 2 1]Do you have a boyfriend?[e]
[f 2 1]That's a tough one.[e]

[msg MSG_013_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 6 65535 65535 0 0][vp 1 0 0 25 0 0]Please, wouldn't you know if I did? We're living under the same roof.[n][w][e]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 26 0 0][f 4 23 0 1 3 25 25]Besides, that's a bit...[n][w][e]

[msg MSG_013_2_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 27 0 0]How do I say this? Romance... just isn't my strong suit.[n][w][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 28 0 0]If I could speak with my father one last time, I would ask him directly.[n][w][e]

[msg MSG_014_2_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 0 0][vp 0 0 0 29 0 0][f 4 23 0 1 3 25 25]......[n][w][e]

[msg MND_015_0_0]
[f 2 1]I lent an ear to Mitsuru...[n][w][e]
[f 2 1]I feel like our relationship has grown...[n][w][e]

[msg MSG_016_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 30 0 0]Looks like we ended up staying until closing time.[n][w][e]

[msg MSG_016_1_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 31 0 0][f 4 23 0 1 1 25 25]Talking in the library... I'm not setting a very good example as student council president.[n][w][e]

[msg MSG_016_2_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 32 0 0][f 4 23 0 1 0 25 25]We should go.[n][w][e]

[msg MND_017_0_0]
[f 2 1]We left the library and returned to the dorm.[n][w][e]

