[msg MSG_000_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 1 0 0]Hm, I dunno about the net café... Why don't we go someplace else?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 2 0 0]Wait, let me see how much money I have...[n][w][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 3 0 0]Oh no! Where's my wallet!? Did I drop it?[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 2 3 25 25]But, when? I had it when I pulled out my train pass...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 5 0 0]Wait... Someone bumped into me outside the station![n][w][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 6 0 0]Sorry, I'm gonna go back there and look around. It'll just take a minute![n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 7 0 0]Make sure you wait right here, okay?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 8 0 0]I'll be fine, so don't come after me![n][w][e]

[msg MSG_002_5_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 9 0 0]Stay right there, you got it!?[n][w][e]

[msg MND_003_0_0]
[f 2 1]Yukari vehemently warned me and ran off...[n][w][e]
[f 2 1]What should I do?[n][w][e]

[sel SEL_004_0_0 top]
[f 2 1]Look around[e]
[f 2 1]Wait here[e]

[msg MND_005_0_0]
[f 2 1]......[n][w][e]
[f 2 1]I'm starting to get weird looks...[n][w][e]
[f 2 1]It doesn't seem like she's coming back...[n][w][e]
[f 2 1]Did something happen...?[n][w][e]

[sel SEL_006_0_0 top]
[f 2 1]Go look for her[e] *
[f 2 1]Wait a bit longer[e]

[msg MND_007_0_0]
[f 2 1]I decided to go check up on her.[n][w][e]

[msg MND_008_0_0]
[f 2 1]......[n][w][e]
[f 2 1]More and more people are staring...[n][w][e]
[f 2 1]Yukari still hasn't come back.[n][w][e]
[f 2 1]I should check up on her.[n][w][e]

