[msg MSG_000_0_0 [Troubled Old Lady]]
[f 2 1][vp 1 0 0 1 0 0][f 5 21 0 1701]Excuse me... Could I trouble you for a moment?[n][w][e]
[f 2 1][vp 1 0 0 2 0 0][f 5 21 0 1701]Have you seen a kitty cat around here?[n][w][e]

[msg MSG_000_3_0 [Troubled Old Lady]]
[f 2 1][vp 1 0 0 3 0 0][f 5 21 0 1701]She's a precious little white, spotted cat named Mii-chan. She slipped away when I wasn't looking.[n][w][e]
[f 2 1][vp 1 0 0 4 0 0][f 5 21 0 1701]I'm so worried about where she could have gone...[n][w][e]

[msg MSG_000_5_0 [Troubled Old Lady]]
[f 2 1][vp 1 0 0 5 0 0][f 5 21 0 1701]She's getting on in her years like me, so I doubt she could have gotten very far.[n][w][e]

[msg MSG_001_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 6 0 0]A white, spotted cat... Did you see one, [nf]-san?[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]I might have...[e] *
[f 2 1]No, I haven't.[e]

[msg MSG_003_0_0 [Troubled Old Lady]]
[f 2 1][vp 1 0 0 7 0 0][f 5 21 0 1701]Goodness, really!? Where might this have been?[n][w][e]

[sel SEL_004_0_0 top]
[f 2 1]Near the station.[e]
[f 2 1]Near the strip mall.[e]
[f 2 1]I don't remember.[e]

[msg MSG_005_0_0 [Troubled Old Lady]]
[f 2 1][vp 1 0 0 8 0 0][f 5 21 0 1701]Thank you, dear! I'll go look for her.[n][w][e]

[msg MSG_006_0_0 [Troubled Old Lady]]
[f 2 1][vp 1 0 0 9 0 0][f 5 21 0 1701]Oh, I see...[n][w][e]
[f 2 1][vp 1 0 0 10 0 0][f 5 21 0 1701]I've been so worried... I hope my little Mii-chan is eating all right...[n][w][e]

[msg MSG_006_3_0 [Troubled Old Lady]]
[f 2 1][vp 1 0 0 11 0 0][f 5 21 0 1701]Thank you for your help. I'll try looking elsewhere.[n][w][e]

[msg MSG_007_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 12 0 0]A white, spotted cat named Mii-chan...[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 13 0 0]If you don't mind, [nf]-san... could we help her look?[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 14 0 0]Being separated from a loved one can be very distressing after all...[n][w][e]

[sel SEL_008_0_0 top]
[f 2 1]All right.[e] *
[f 2 1]What a pain...[e]

[msg MSG_009_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 15 0 0][f 5 13 22 15 7]Yes![n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 16 0 0][f 4 23 0 7 0 25 25]Um, what's the phrase usually used in situations like these?[n][w][e]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 17 0 0][f 4 23 0 7 1 25 25][f 4 21 7 7]"What goes around, comes around to hit you in the back of the head"![n][w][e]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 18 0 0]That's it![n][w][e]

[msg MSG_010_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 19 0 0]But if they remain separated, she will feel the same pain that Koromaru-san once did...[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 20 0 0][f 4 23 0 7 0 25 25]If we help, I think we can at least reduce the chances of that happening![n][w][e]

[msg MND_011_0_0]
[f 2 1]It seems I can't turn her down.[n][w][e]

[msg MSG_012_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 21 0 0]She might be so hungry she could eat a house.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 0 0 0 22 0 0]......[n][w][e]

[msg MSG_012_3_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 23 0 0]Or was it, "hungry as a house"?[n][w][e]

[msg MSG_012_4_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 24 0 0]In any case, we should hurry.[n][w][e]

